const DELIVERY_PAYLOAD_CONTRACT_VERSION='cp43.portal_invitation_delivery_payload.v1';const AES_GCM_NONCE_BYTES=12;const AES_256_KEY_BYTES=32
export interface EncryptedPortalInvitationDeliveryPayload{ciphertext:string;nonce:string;keyVersion:string;createdAt:string;expiresAt:string}
function base64UrlEncode(bytes:Uint8Array):string{let binary='';for(const byte of bytes)binary+=String.fromCharCode(byte);return btoa(binary).replaceAll('+','-').replaceAll('/','_').replace(/=+$/u,'')}
function base64UrlDecode(value:string):Uint8Array{if(!/^[A-Za-z0-9_-]+$/u.test(value))throw new Error('portal_invitation_delivery_payload_invalid');const padded=value.replaceAll('-','+').replaceAll('_','/')+'='.repeat((4-value.length%4)%4);try{const binary=atob(padded);return Uint8Array.from(binary,(character)=>character.charCodeAt(0))}catch{throw new Error('portal_invitation_delivery_payload_invalid')}}
function requireOpaque(value:string,field:string):string{const normalized=value.trim();if(!normalized||normalized.length>160)throw new Error(`portal_invitation_delivery_${field}_invalid`);return normalized}
function assertExpiresAt(value:string,now:Date):string{const timestamp=Date.parse(value);if(!Number.isFinite(timestamp)||timestamp<=now.getTime())throw new Error('portal_invitation_delivery_payload_expired');return new Date(timestamp).toISOString()}
function additionalData(invitationId:string,keyVersion:string,expiresAt:string):Uint8Array{return new TextEncoder().encode(`${DELIVERY_PAYLOAD_CONTRACT_VERSION}:${invitationId}:${keyVersion}:${expiresAt}`)}
async function importEncryptionKey(secret:string):Promise<CryptoKey>{const bytes=base64UrlDecode(secret.trim());if(bytes.byteLength!==AES_256_KEY_BYTES)throw new Error('portal_invitation_delivery_key_invalid');return crypto.subtle.importKey('raw',bytes,{name:'AES-GCM'},false,['encrypt','decrypt'])}
export async function encryptPortalInvitationDeliveryToken(input:{token:string;invitationId:string;keyVersion:string;expiresAt:string;encryptionKey:string;now?:()=>Date}):Promise<EncryptedPortalInvitationDeliveryPayload>{const invitationId=requireOpaque(input.invitationId,'invitation_id');const keyVersion=requireOpaque(input.keyVersion,'key_version');const now=input.now?.()??new Date();const expiresAt=assertExpiresAt(input.expiresAt,now);const token=requireOpaque(input.token,'token');const nonce=crypto.getRandomValues(new Uint8Array(AES_GCM_NONCE_BYTES));const ciphertext=await crypto.subtle.encrypt({name:'AES-GCM',iv:nonce,additionalData:additionalData(invitationId,keyVersion,expiresAt),tagLength:128},await importEncryptionKey(input.encryptionKey),new TextEncoder().encode(token));return{ciphertext:base64UrlEncode(new Uint8Array(ciphertext)),nonce:base64UrlEncode(nonce),keyVersion,createdAt:now.toISOString(),expiresAt}}
export async function decryptPortalInvitationDeliveryToken(input:{payload:EncryptedPortalInvitationDeliveryPayload;invitationId:string;encryptionKey:string;now?:()=>Date}):Promise<string>{const invitationId=requireOpaque(input.invitationId,'invitation_id');const keyVersion=requireOpaque(input.payload.keyVersion,'key_version');const expiresAt=assertExpiresAt(input.payload.expiresAt,input.now?.()??new Date());try{const plaintext=await crypto.subtle.decrypt({name:'AES-GCM',iv:base64UrlDecode(input.payload.nonce),additionalData:additionalData(invitationId,keyVersion,expiresAt),tagLength:128},await importEncryptionKey(input.encryptionKey),base64UrlDecode(input.payload.ciphertext));const token=new TextDecoder().decode(plaintext);return requireOpaque(token,'token')}catch(error){if(error instanceof Error&&error.message==='portal_invitation_delivery_payload_expired')throw error;throw new Error('portal_invitation_delivery_payload_invalid')}}
