import { useState, type ChangeEvent } from 'react'
import type { ClientListItem } from '../../features/clients/types'; import { findPropertyDuplicateGroups } from '../../features/duplicates/duplicateEngine'; import type { PropertyListItem } from '../../features/properties/types'; import { fetchAuthenticatedSupabaseWrite, readSingleAuthenticatedWriteRow } from '../../lib/authenticatedSupabaseWrite'; import { operationalWriteRpcPaths } from '../../lib/operationalWriteRpc'
import { V3Field, V3Input, V3Select, V3Textarea } from '../components/V3Primitives'; import { V3StepFlow } from '../stepflow/V3StepFlow'
interface Props { mode: 'create' | 'edit'; property?: PropertyListItem | null; clients: ClientListItem[]; properties: PropertyListItem[]; onRefresh: () => Promise<void>; onCompleted: (property?: PropertyListItem) => Promise<void>; onCancel: () => void; onOpenClients?: () => void }
type FormState = { client_id: string; name: string; property_type: string; address: string; city: string; postal_code: string; notes: string }
const initial = (property: PropertyListItem | null | undefined, clients: ClientListItem[]): FormState => ({ client_id: property?.client_id ?? clients[0]?.id ?? '', name: property?.name ?? '', property_type: property?.property_type ?? 'apartment', address: property?.address ?? '', city: property?.city ?? '', postal_code: property?.postal_code ?? '', notes: property?.notes ?? '' })
export function V3PropertyWriteFlow({ mode, property = null, clients, properties, onRefresh, onCompleted, onCancel, onOpenClients }: Props) {
  const [value, setValue] = useState(() => initial(property, clients)); const [error, setError] = useState<string | null>(null); const [busy, setBusy] = useState(false); const [duplicateFound, setDuplicateFound] = useState(false)
  const update = (key: keyof FormState) => (event: ChangeEvent<HTMLInputElement | HTMLTextAreaElement | HTMLSelectElement>) => setValue((current) => ({ ...current, [key]: event.target.value }))
  async function submit() { setError(null); if (!value.client_id) return setError('Debes seleccionar un cliente.'); if (!value.name.trim()) return setError('Debes indicar un nombre interno para el inmueble.'); if (!value.address.trim()) return setError('Debes indicar la dirección operativa del inmueble.'); const client = clients.find((item) => item.id === value.client_id); const draft: PropertyListItem = { id: property?.id ?? 'PROPERTY-DRAFT', display_code: property?.display_code ?? null, client_id: value.client_id, client_display_code: client?.display_code ?? null, client_name: client?.full_name ?? null, name: value.name.trim(), status: property?.status ?? 'active', archived_at: property?.archived_at ?? null, deleted_at: property?.deleted_at ?? null, property_type: value.property_type, address: value.address.trim(), city: value.city.trim() || null, postal_code: value.postal_code.trim() || null, notes: value.notes.trim() || null }; if (findPropertyDuplicateGroups(draft, properties.filter((item) => item.id !== property?.id)).length) return setDuplicateFound(true); setBusy(true); try { const id = property?.id ?? (typeof crypto !== 'undefined' && typeof crypto.randomUUID === 'function' ? `PROPERTY-${crypto.randomUUID()}` : `PROPERTY-${Date.now()}`); const path = property ? operationalWriteRpcPaths.updateProperty : operationalWriteRpcPaths.createProperty; const response = await fetchAuthenticatedSupabaseWrite(path, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ p_property: { id, client_id: value.client_id, name: value.name.trim(), property_type: value.property_type, address: value.address.trim(), city: value.city.trim() || null, postal_code: value.postal_code.trim() || null, notes: value.notes.trim() || null } }) }); const row = await readSingleAuthenticatedWriteRow<Partial<PropertyListItem>>(response, 'El inmueble no se pudo guardar. Revisa tu sesión o permisos.'); await onRefresh(); await onCompleted({ ...draft, ...row, id: row?.id ?? id }); } catch (cause) { setError(cause instanceof Error ? cause.message : 'No se pudo guardar el inmueble.') } finally { setBusy(false) } }
  if (clients.length === 0 && mode === 'create') return <div className="v3-property-create-empty"><p>Necesitas un cliente antes de crear un inmueble.</p>{onOpenClients ? <button type="button" className="v3-action v3-action--primary" onClick={onOpenClients}>Ir a Clientes V3</button> : null}</div>
  const typeFields = <><V3Field label="Tipo"><V3Select value={value.property_type} onChange={update('property_type')}><option value="apartment">Apartamento</option><option value="house">Casa</option><option value="office">Oficina</option><option value="local">Local</option><option value="tourist_apartment">Piso turístico</option><option value="community">Comunidad</option><option value="construction_site">Obra</option></V3Select></V3Field><V3Field label="Dirección"><V3Input value={value.address} onChange={update('address')} required /></V3Field><V3Field label="Ciudad"><V3Input value={value.city} onChange={update('city')} /></V3Field><V3Field label="Código postal"><V3Input value={value.postal_code} onChange={update('postal_code')} /></V3Field></>
  return <V3StepFlow title={mode === 'create' ? 'Nuevo inmueble' : 'Editar inmueble'} onCancel={onCancel} onComplete={submit} error={error || (duplicateFound ? 'Ya existe una coincidencia con este cliente y dirección.' : null)} busy={busy} completeLabel={mode === 'create' ? 'Crear inmueble' : 'Guardar cambios'} validateStep={(step) => step === 0 && (!value.client_id || !value.name.trim()) ? 'Cliente y nombre son obligatorios.' : step === 1 && !value.address.trim() ? 'Indica la dirección operativa.' : null} steps={[{ id: 'identity', title: 'Identidad', description: 'Asigna el inmueble a un cliente.', content: <><V3Field label="Cliente"><V3Select value={value.client_id} onChange={update('client_id')} required autoFocus>{clients.map((client) => <option key={client.id} value={client.id}>{client.full_name}</option>)}</V3Select></V3Field><V3Field label="Nombre"><V3Input value={value.name} onChange={update('name')} required /></V3Field></> }, { id: 'address', title: 'Ubicación', description: 'Define el contexto operativo del inmueble.', content: <>{typeFields}</> }, { id: 'notes', title: 'Notas y revisión', description: 'Confirma los datos antes de guardar.', content: <V3Field label="Notas"><V3Textarea value={value.notes} onChange={update('notes')} /></V3Field> }]} />
}
