import { useEffect, useMemo, useRef, useState } from 'react'
import { findExpenseDuplicateGroups } from '../../features/duplicates/duplicateEngine'
import { uploadExpenseReceipt } from '../../features/expenses/expenseAttachmentsApi'
import { createExpense, updateExpense, updateExpenseAttachment } from '../../features/expenses/expenseApi'
import { expenseCategories, expenseDocumentSupportStatuses, expenseDocumentTypes, expenseFiscalReviewStatuses, expenseFiscalRiskLevels, expensePaymentStatuses, type ExpenseListItem, type ExpenseUpsertInput } from '../../features/expenses/types'
import { V3Field, V3Input, V3Select, V3Textarea } from '../components/V3Primitives'
import { V3StepFlow } from '../stepflow/V3StepFlow'

interface Props { mode: 'create' | 'edit'; expense?: ExpenseListItem | null; expenses: ExpenseListItem[]; onRefresh: () => Promise<void>; onCompleted: () => void | Promise<void>; onCancel: () => void; onDirtyChange?: (dirty: boolean) => void }
type FormState = { expense_date: string; supplier_name: string; category: string; description: string; document_type: string; payment_status: string; subtotal: string; tax_rate: string; notes: string; document_support_status: string; fiscal_review_status: string; fiscal_risk_level: string; manager_note: string }
const money = (value: string) => { const parsed = Number(value.replace(',', '.')); return Number.isFinite(parsed) ? parsed : Number.NaN }
const expenseLabels: Record<string, string> = { materiales: 'Materiales', transporte: 'Transporte', combustible: 'Combustible', herramientas: 'Herramientas', productos_limpieza: 'Productos de limpieza', lavanderia: 'Lavandería', alquiler: 'Alquiler', seguros: 'Seguros', software: 'Software', telefonia: 'Telefonía', publicidad_marketing: 'Publicidad y marketing', gestoria: 'Gestoría', suministros: 'Suministros', mantenimiento: 'Mantenimiento', dietas_viajes: 'Dietas y viajes', impuestos_tasas: 'Impuestos y tasas', servicios_profesionales: 'Servicios profesionales', otros: 'Otros', ticket: 'Ticket', invoice: 'Factura', receipt: 'Recibo', paid: 'Pagado', pending: 'Pendiente', missing: 'Sin soporte', attached: 'Con soporte', reviewed: 'Revisado', low: 'Bajo', medium: 'Medio', high: 'Alto' }
const expenseLabel = (value: string) => expenseLabels[value] ?? value
function initial(expense?: ExpenseListItem | null): FormState { return { expense_date: expense?.expense_date ?? new Date().toISOString().slice(0, 10), supplier_name: expense?.supplier_name ?? '', category: expense?.category ?? 'otros', description: expense?.description ?? '', document_type: expense?.document_type ?? 'ticket', payment_status: expense?.payment_status ?? 'paid', subtotal: String(expense?.subtotal ?? ''), tax_rate: String(expense?.tax_rate ?? 21), notes: expense?.notes ?? '', document_support_status: expense?.document_support_status ?? 'missing', fiscal_review_status: expense?.fiscal_review_status ?? 'pending', fiscal_risk_level: expense?.fiscal_risk_level ?? 'medium', manager_note: expense?.manager_note ?? '' } }

export function V3ExpenseFormFlow({ mode, expense = null, expenses, onRefresh, onCompleted, onCancel, onDirtyChange }: Props) {
  const [form, setForm] = useState(() => initial(expense)); const [file, setFile] = useState<File | null>(null); const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null); const [dirty, setDirty] = useState(false); const baselineRef = useRef(JSON.stringify({ form: initial(expense), file: null }))
  useEffect(() => { onDirtyChange?.(dirty); return () => onDirtyChange?.(false) }, [dirty, onDirtyChange])
  useEffect(() => { setDirty(JSON.stringify({ form, file: file?.name ?? null }) !== baselineRef.current) }, [form, file])
  const subtotal = useMemo(() => money(form.subtotal), [form.subtotal]); const taxRate = useMemo(() => money(form.tax_rate), [form.tax_rate]); const tax = Number.isFinite(subtotal) && Number.isFinite(taxRate) ? Math.round(subtotal * taxRate) / 100 : Number.NaN; const total = Number.isFinite(subtotal) && Number.isFinite(tax) ? Math.round((subtotal + tax) * 100) / 100 : Number.NaN
  function set<K extends keyof FormState>(key: K, value: FormState[K]) { setForm((current) => ({ ...current, [key]: value })) }
  async function submit() {
    setError(null); if (!form.expense_date || !form.supplier_name.trim() || !form.description.trim()) return setError('Fecha, proveedor y descripción son obligatorios.'); if (!Number.isFinite(subtotal) || !Number.isFinite(taxRate)) return setError('Base imponible e IVA deben ser números válidos.')
    const candidate = { ...(expense ?? { id: `EXPENSE-DRAFT-${Date.now()}`, expense_date: form.expense_date, supplier_name: form.supplier_name, category: form.category, description: form.description, document_type: form.document_type, payment_status: form.payment_status, subtotal, tax_rate: taxRate, tax_amount: tax, total, is_deductible: true, deductible_percentage: 100, affects_quarterly_closure: true, affects_annual_closure: true, receipt_file_url: null, receipt_file_path: null, attachment_count: 0, document_support_status: form.document_support_status, fiscal_review_status: form.fiscal_review_status, fiscal_risk_level: form.fiscal_risk_level, manager_note: form.manager_note || null, notes: form.notes || null } as ExpenseListItem), expense_date: form.expense_date, supplier_name: form.supplier_name, category: form.category, description: form.description, document_type: form.document_type, payment_status: form.payment_status, subtotal, tax_rate: taxRate, tax_amount: tax, total, document_support_status: form.document_support_status, fiscal_review_status: form.fiscal_review_status, fiscal_risk_level: form.fiscal_risk_level, manager_note: form.manager_note || null, notes: form.notes || null }
    if (findExpenseDuplicateGroups(candidate, expenses).filter((group) => !expense || group.records.some((record) => record.recordId !== expense.id)).length) return setError('Ya existe un gasto con el mismo contexto. Revisa el gasto existente antes de guardar.')
    const payload: ExpenseUpsertInput = { expense_date: form.expense_date, supplier_name: form.supplier_name, category: form.category, description: form.description, document_type: form.document_type, payment_status: form.payment_status, subtotal, tax_rate: taxRate, tax_amount: tax, total, is_deductible: expense?.is_deductible ?? true, deductible_percentage: expense?.deductible_percentage ?? 100, document_support_status: form.document_support_status, fiscal_review_status: form.fiscal_review_status, fiscal_risk_level: form.fiscal_risk_level, manager_note: form.manager_note || null, notes: form.notes || null }
    setBusy(true); try { const id = expense ? (await updateExpense(expense.id, payload), expense.id) : await createExpense(payload); if (file) { const uploaded = await uploadExpenseReceipt(id, file); await updateExpenseAttachment(id, uploaded.filePath) }; setDirty(false); onDirtyChange?.(false); await onRefresh(); await onCompleted() } catch (cause) { setError(cause instanceof Error ? cause.message : 'No se pudo guardar el gasto.') } finally { setBusy(false) }
  }
  return <V3StepFlow title={mode === 'create' ? 'Nuevo gasto' : 'Editar gasto'} onCancel={onCancel} onComplete={submit} error={error} busy={busy} completeLabel="Guardar gasto" validateStep={(step) => step === 0 && (!form.expense_date || !form.supplier_name.trim() || !form.description.trim()) ? 'Fecha, proveedor y descripción son obligatorios.' : step === 1 && (!Number.isFinite(subtotal) || !Number.isFinite(taxRate)) ? 'Base imponible e IVA deben ser números válidos.' : null} steps={[
    { id: 'basics', title: 'Datos básicos', description: '¿Qué gasto es y quién lo emitió?', content: <><V3Field label="Proveedor"><V3Input value={form.supplier_name} onChange={(event) => set('supplier_name', event.target.value)} required autoFocus /></V3Field><V3Field label="Fecha"><V3Input type="date" value={form.expense_date} onChange={(event) => set('expense_date', event.target.value)} required /></V3Field><V3Field label="Categoría"><V3Select value={form.category} onChange={(event) => set('category', event.target.value)}>{expenseCategories.map((value) => <option key={value} value={value}>{expenseLabel(value)}</option>)}</V3Select></V3Field><V3Field label="Descripción"><V3Input value={form.description} onChange={(event) => set('description', event.target.value)} required /></V3Field></> },
    { id: 'amount', title: 'Importe e impuestos', description: 'El total se calcula con la base y el IVA.', content: <><V3Field label="Base imponible"><V3Input inputMode="decimal" value={form.subtotal} onChange={(event) => set('subtotal', event.target.value)} required /></V3Field><V3Field label="IVA %"><V3Input inputMode="decimal" value={form.tax_rate} onChange={(event) => set('tax_rate', event.target.value)} required /></V3Field><p className="v3-expense-form-total" role="status"><span>Total calculado</span><strong>{Number.isFinite(total) ? `${total.toFixed(2)} €` : 'Pendiente'}</strong></p></> },
    { id: 'support', title: 'Documento y pago', description: 'Clasifica el soporte y el estado operativo.', content: <><V3Field label="Tipo de documento"><V3Select value={form.document_type} onChange={(event) => set('document_type', event.target.value)}>{expenseDocumentTypes.map((value) => <option key={value} value={value}>{expenseLabel(value)}</option>)}</V3Select></V3Field><V3Field label="Estado de pago"><V3Select value={form.payment_status} onChange={(event) => set('payment_status', event.target.value)}>{expensePaymentStatuses.map((value) => <option key={value} value={value}>{expenseLabel(value)}</option>)}</V3Select></V3Field><V3Field label="Documento (opcional, máximo 10 MB)"><V3Input type="file" accept="application/pdf,image/jpeg,image/png,image/webp" onChange={(event) => setFile(event.target.files?.[0] ?? null)} /></V3Field></> },
    { id: 'review', title: 'Revisión fiscal', description: 'Deja el gasto listo para revisión interna.', content: <><V3Field label="Soporte"><V3Select value={form.document_support_status} onChange={(event) => set('document_support_status', event.target.value)}>{expenseDocumentSupportStatuses.map((value) => <option key={value} value={value}>{expenseLabel(value)}</option>)}</V3Select></V3Field><V3Field label="Revisión"><V3Select value={form.fiscal_review_status} onChange={(event) => set('fiscal_review_status', event.target.value)}>{expenseFiscalReviewStatuses.map((value) => <option key={value} value={value}>{expenseLabel(value)}</option>)}</V3Select></V3Field><V3Field label="Riesgo"><V3Select value={form.fiscal_risk_level} onChange={(event) => set('fiscal_risk_level', event.target.value)}>{expenseFiscalRiskLevels.map((value) => <option key={value} value={value}>{expenseLabel(value)}</option>)}</V3Select></V3Field></> },
    { id: 'notes', title: 'Notas y resumen', description: 'Comprueba el importe y añade contexto opcional.', content: <><p className="v3-inline-message">Total del gasto: {Number.isFinite(total) ? `${total.toFixed(2)} €` : 'Pendiente'}</p><V3Field label="Notas"><V3Textarea value={form.notes} onChange={(event) => set('notes', event.target.value)} /></V3Field><V3Field label="Nota del responsable"><V3Textarea value={form.manager_note} onChange={(event) => set('manager_note', event.target.value)} /></V3Field></> },
  ]} />
}
