import { describe, expect, it } from 'vitest'
import { normalizeExpenseProposal } from './expenseNormalization'
import { createMissingField, type ExtractionProposal } from './expenseExtractionContract'
const field = <T>(value: T, rawValue = String(value)) => ({ value, rawValue, confidence: 0.94, source: 'document' as const })
const proposal = (): ExtractionProposal => ({ schemaVersion: 1, documentType: field('INVOICE'), supplier: { rawName: field('Supplier'), legalNameCandidate: createMissingField(), commercialNameCandidate: createMissingField(), taxId: field('12345678Z'), normalizedTaxIdCandidate: createMissingField(), vatId: createMissingField(), address: createMissingField(), postalCode: createMissingField(), city: createMissingField(), country: createMissingField(), phone: createMissingField(), email: createMissingField(), website: createMissingField() }, invoice: { number: field('FA-00234'), issueDate: field('28/09/2026'), dueDate: createMissingField(), currency: field('€') }, amounts: { net: field('100.00'), tax: field('21.00'), gross: field('121.00'), discount: createMissingField(), withholding: createMissingField() }, vatLines: [{ rate: field('21'), base: field('100.00'), tax: field('21.00') }], payment: { method: createMissingField() }, confidence: { overall: 0.94 } })
describe('N5.3 reconciliation and immutability', () => {
  it('normalizes without mutating extraction evidence and preserves meaningful spaces', () => { const input = proposal(); input.supplier.rawName = field('  Supplier   Name  '); input.supplier.address = field(' Main   Street 25 '); input.invoice.number = field(' AB 00123 '); const before = structuredClone(input); const output = normalizeExpenseProposal(input); expect(input).toEqual(before); expect(output.supplier.rawName.normalizedValue).toBe('Supplier Name'); expect(output.supplier.address.normalizedValue).toBe('Main Street 25'); expect(output.invoice.number.normalizedValue).toBe('AB 00123'); expect(output.invoice.currency.normalizedValue).toBe('EUR'); expect(output.reconciliation.status).toBe('MATCH'); expect(output.reviewStatus).toBe('READY_FOR_REVIEW'); expect(output).not.toHaveProperty('confirmed') })
  it('keeps confidence separate from validation conflicts', () => { const input = proposal(); input.amounts.gross = field('120.00'); const output = normalizeExpenseProposal(input); expect(output.confidence.overall).toBe(0.94); expect(output.reconciliation.status).toBe('MISMATCH'); expect(output.reviewStatus).toBe('BLOCKED') })
  it('does not force discounts or withholding into a simple identity', () => { const input = proposal(); input.amounts.discount = field('5.00'); const output = normalizeExpenseProposal(input); expect(output.reconciliation.status).toBe('COMPLEX_ADJUSTMENT'); expect(output.reviewStatus).toBe('NEEDS_ATTENTION') })
  it('accepts negative credit-note amounts and validates VAT rates', () => { const input = proposal(); input.documentType = field('CREDIT_NOTE'); input.amounts.net = field('-100.00'); input.amounts.tax = field('-21.00'); input.amounts.gross = field('-121.00'); input.vatLines = [{ rate: field('21'), base: field('-100.00'), tax: field('-21.00') }]; const output = normalizeExpenseProposal(input); expect(output.reconciliation.status).toBe('MATCH'); expect(output.issues.some((item) => item.code === 'VAT_RATE_INVALID')).toBe(false); input.vatLines[0].rate = field('101'); expect(normalizeExpenseProposal(input).issues.some((item) => item.code === 'VAT_RATE_INVALID')).toBe(true) })
  it('accepts legitimate VAT rates and rejects values outside the inclusive range', () => { for (const rate of ['0', '4', '10', '21', '5.5']) { const input = proposal(); input.vatLines = [{ rate: field<`${number}`>(rate as `${number}`), base: field<`${number}`>('100.00'), tax: field<`${number}`>('21.00') }]; expect(normalizeExpenseProposal(input).issues.some((item) => item.code === 'VAT_RATE_INVALID')).toBe(false) } const negative = proposal(); negative.vatLines[0].rate = field<`${number}`>('-1'); expect(normalizeExpenseProposal(negative).issues.some((item) => item.code === 'VAT_RATE_INVALID')).toBe(true); const over = proposal(); over.vatLines[0].rate = field<`${number}`>('100.01'); expect(normalizeExpenseProposal(over).issues.some((item) => item.code === 'VAT_RATE_INVALID')).toBe(true) })
  it('does not require an invoice number for receipts', () => { const input = proposal(); input.documentType = field('RECEIPT'); input.invoice.number = createMissingField(); const output = normalizeExpenseProposal(input); expect(output.invoice.number.status).toBe('MISSING'); expect(output.issues.some((item) => item.code === 'INVOICE_NUMBER_MISSING')).toBe(false); expect(output.reviewStatus).toBe('READY_FOR_REVIEW') })
  it('normalizes supported currencies deterministically without EUR fallback', () => { for (const [raw, normalized] of [['eur', 'EUR'], ['EUR', 'EUR'], ['€', 'EUR'], ['usd', 'USD'], ['USD', 'USD'], ['gbp', 'GBP'], ['CHF', 'CHF']] as const) { const input = proposal(); input.invoice.currency = field(raw); const output = normalizeExpenseProposal(input); expect(output.invoice.currency.normalizedValue).toBe(normalized); expect(output.invoice.currency.status).toBe('VALID') } const missing = proposal(); missing.invoice.currency = createMissingField(); expect(normalizeExpenseProposal(missing).invoice.currency.status).toBe('MISSING'); for (const raw of ['USD?', 'EURO?', '123', 'ZZZ']) { const input = proposal(); input.invoice.currency = field(raw); const output = normalizeExpenseProposal(input); expect(output.invoice.currency.status).toBe('INVALID'); expect(output.issues.some((item) => item.code === 'UNKNOWN_CURRENCY')).toBe(true) } })
  it('requires issue dates for invoice, receipt, and credit note but keeps due date optional', () => { for (const documentType of ['INVOICE', 'RECEIPT', 'CREDIT_NOTE'] as const) { const input = proposal(); input.documentType = field(documentType); input.invoice.issueDate = createMissingField(); const output = normalizeExpenseProposal(input); const missing = output.issues.find((item) => item.code === 'FIELD_MISSING' && item.field === 'invoice.issueDate'); expect(missing?.severity).toBe('ERROR'); expect(missing?.blocking).toBe(true); expect(output.reviewStatus).toBe('BLOCKED') } const optional = proposal(); optional.invoice.dueDate = createMissingField(); const output = normalizeExpenseProposal(optional); expect(output.issues.some((item) => item.code === 'FIELD_MISSING' && item.field === 'invoice.dueDate')).toBe(false); expect(output.reviewStatus).toBe('READY_FOR_REVIEW') })
  it('treats partial VAT lines as insufficient data and applies exact cent tolerance', () => { const input = proposal(); input.vatLines = [{ rate: field('10'), base: field('50.00'), tax: field('5.00') }, { rate: field('21'), base: createMissingField(), tax: field('21.00') }]; input.amounts.net = field('150.00'); input.amounts.tax = field('26.00'); input.amounts.gross = field('176.00'); expect(normalizeExpenseProposal(input).reconciliation.status).toBe('INSUFFICIENT_DATA'); input.vatLines = [{ rate: field('21'), base: field('100.00'), tax: field('21.00') }]; input.amounts.net = field('100.00'); input.amounts.tax = field('21.00'); input.amounts.gross = field('121.01'); expect(normalizeExpenseProposal(input).reconciliation.status).toBe('MATCH'); input.amounts.gross = field('121.02'); expect(normalizeExpenseProposal(input).reconciliation.status).toBe('MISMATCH') })
  it('is deterministic', () => { const input = proposal(); expect(normalizeExpenseProposal(input)).toEqual(normalizeExpenseProposal(input)) })
})
