import { describe, expect, it } from 'vitest'
import { normalizeExpenseProposal } from './expenseNormalization'
import { createMissingField, type ExtractionProposal } from './expenseExtractionContract'
const field = <T>(value: T, rawValue = String(value)) => ({ value, rawValue, confidence: 0.94, source: 'document' as const })
const proposal = (): ExtractionProposal => ({ schemaVersion: 1, documentType: field('INVOICE'), supplier: { rawName: field('Supplier'), legalNameCandidate: createMissingField(), commercialNameCandidate: createMissingField(), taxId: field('12345678Z'), normalizedTaxIdCandidate: createMissingField(), vatId: createMissingField(), address: createMissingField(), postalCode: createMissingField(), city: createMissingField(), country: createMissingField(), phone: createMissingField(), email: createMissingField(), website: createMissingField() }, invoice: { number: field('FA-00234'), issueDate: field('28/09/2026'), dueDate: createMissingField(), currency: field('€') }, amounts: { net: field('100.00'), tax: field('21.00'), gross: field('121.00'), discount: createMissingField(), withholding: createMissingField() }, vatLines: [{ rate: field('21'), base: field('100.00'), tax: field('21.00') }], payment: { method: createMissingField() }, confidence: { overall: 0.94 } })
describe('N5.3 reconciliation and immutability', () => {
  it('normalizes without mutating extraction evidence', () => { const input = proposal(); const before = structuredClone(input); const output = normalizeExpenseProposal(input); expect(input).toEqual(before); expect(output.invoice.currency.normalizedValue).toBe('EUR'); expect(output.reconciliation.status).toBe('MATCH'); expect(output.reviewStatus).toBe('NEEDS_ATTENTION'); expect(output).not.toHaveProperty('confirmed') })
  it('keeps confidence separate from validation conflicts', () => { const input = proposal(); input.amounts.gross = field('120.00'); const output = normalizeExpenseProposal(input); expect(output.confidence.overall).toBe(0.94); expect(output.reconciliation.status).toBe('MISMATCH'); expect(output.reviewStatus).toBe('BLOCKED') })
  it('does not force discounts or withholding into a simple identity', () => { const input = proposal(); input.amounts.discount = field('5.00'); const output = normalizeExpenseProposal(input); expect(output.reconciliation.status).toBe('COMPLEX_ADJUSTMENT'); expect(output.reviewStatus).toBe('NEEDS_ATTENTION') })
  it('accepts negative credit-note amounts and validates VAT rates', () => { const input = proposal(); input.documentType = field('CREDIT_NOTE'); input.amounts.net = field('-100.00'); input.amounts.tax = field('-21.00'); input.amounts.gross = field('-121.00'); input.vatLines = [{ rate: field('21'), base: field('-100.00'), tax: field('-21.00') }]; const output = normalizeExpenseProposal(input); expect(output.reconciliation.status).toBe('MATCH'); expect(output.issues.some((item) => item.code === 'VAT_RATE_INVALID')).toBe(false); input.vatLines[0].rate = field('101'); expect(normalizeExpenseProposal(input).issues.some((item) => item.code === 'VAT_RATE_INVALID')).toBe(true) })
  it('does not infer unknown currency', () => { const input = proposal(); input.invoice.currency = field('USD?'); const output = normalizeExpenseProposal(input); expect(output.invoice.currency.normalizedValue).toBe('USD?'); expect(output.issues.some((item) => item.code === 'UNKNOWN_CURRENCY')).toBe(true) })
  it('is deterministic', () => { const input = proposal(); expect(normalizeExpenseProposal(input)).toEqual(normalizeExpenseProposal(input)) })
})
