import { normalizeDecimal } from './expenseNormalizationDecimals'
import { decimalCompare } from './expenseNormalizationDecimals'
import { normalizeDate } from './expenseNormalizationDates'
import { deriveReviewStatus, issue, reconcileAmounts } from './expenseNormalizationValidation'
import { normalizeTaxId } from './expenseNormalizationTaxId'
import type { ExtractionProposal, ExtractedField } from './expenseExtractionContract'
import type { NormalizedExpenseProposal, NormalizedField, NormalizationStatus, ValidationIssue } from './expenseNormalizationContract'

function field<T>(source: ExtractedField<T>, normalizedValue: T | null, status: NormalizationStatus, issues: ValidationIssue[] = []): NormalizedField<T> { return { rawValue: source.rawValue, extractedValue: source.value, normalizedValue, confidence: source.confidence, source: source.source, evidence: source.evidence, status, issues } }
function confidenceIssue(name: string, source: ExtractedField<unknown>): ValidationIssue[] { return source.confidence !== null && source.confidence < 0.7 ? [issue('LOW_CONFIDENCE', name, 'WARNING', false, 'provider confidence is below review threshold')] : [] }
function textField(source: ExtractedField<string>, name: string): NormalizedField<string> { const value = source.value?.trim().replace(/\s+/gu, '') ?? null; const missing = value === null || value === ''; const issues = [...confidenceIssue(name, source), ...(missing ? [issue('FIELD_MISSING', name, 'WARNING', false, 'field was not detected')] : [])]; return field(source, missing ? null : value, missing ? 'MISSING' : 'VALID', issues) }
function decimalField(source: ExtractedField<string>, name: string): NormalizedField<string> { const result = normalizeDecimal(source.value); const issues = [...confidenceIssue(name, source), ...(result.status === 'AMBIGUOUS' ? [issue('FIELD_AMBIGUOUS', name, 'ERROR', true, 'decimal interpretation is ambiguous')] : []), ...(result.status === 'INVALID' ? [issue('INVALID_DECIMAL', name, 'ERROR', true, 'decimal is invalid')] : [])]; return field(source, result.value, result.status as NormalizationStatus, issues) }
function dateField(source: ExtractedField<string>, name: string): NormalizedField<string> { const result = normalizeDate(source.value); const code = result.status === 'AMBIGUOUS' ? 'FIELD_AMBIGUOUS' : result.status === 'INVALID' ? 'INVALID_DATE' : result.status === 'MISSING' ? 'FIELD_MISSING' : ''; const issues = [...confidenceIssue(name, source), ...(code ? [issue(code, name, result.status === 'MISSING' ? 'WARNING' : 'ERROR', result.status !== 'MISSING', 'date requires review')] : [])]; return field(source, result.value, result.status as NormalizationStatus, issues) }
function currencyField(source: ExtractedField<string>): NormalizedField<string> { const value = source.value?.trim().toUpperCase() ?? null; const normalized = value === '€' || value === 'EUR' ? 'EUR' : value === null || value === '' ? null : value; const status = normalized === null ? 'MISSING' : normalized === 'EUR' ? 'VALID' : 'INVALID'; const issues = status === 'INVALID' ? [issue('UNKNOWN_CURRENCY', 'invoice.currency', 'ERROR', true, 'currency is not recognized')] : status === 'MISSING' ? [issue('FIELD_MISSING', 'invoice.currency', 'WARNING', false, 'currency was not detected')] : []; return field(source, normalized, status, issues) }
function taxField(source: ExtractedField<string>): NormalizedField<string> { const result = normalizeTaxId(source.value); const issues = result.status === 'INVALID' ? [issue('INVALID_TAX_ID', 'supplier.taxId', 'ERROR', true, 'tax identifier checksum or format is invalid')] : []; return field(source, result.normalizedValue, result.status === 'UNKNOWN_FORMAT' ? 'AMBIGUOUS' : result.status, issues) }
const supplierKeys = ['rawName', 'legalNameCandidate', 'commercialNameCandidate', 'taxId', 'normalizedTaxIdCandidate', 'vatId', 'address', 'postalCode', 'city', 'country', 'phone', 'email', 'website'] as const
export function normalizeExpenseProposal(input: ExtractionProposal): NormalizedExpenseProposal {
  const source = structuredClone(input)
  const allIssues: ValidationIssue[] = []
  const documentType = textField(input.documentType as ExtractedField<string>, 'documentType'); if (documentType.normalizedValue === null || documentType.normalizedValue === 'UNKNOWN') allIssues.push(issue('DOCUMENT_TYPE_UNKNOWN', 'documentType', 'WARNING', false, 'document type needs human review'))
  const supplier = Object.fromEntries(supplierKeys.map((key) => [key, key === 'taxId' || key === 'normalizedTaxIdCandidate' ? taxField(input.supplier[key]) : textField(input.supplier[key], `supplier.${key}`)])) as Record<string, NormalizedField<string>>
  const invoice = { number: textField(input.invoice.number, 'invoice.number'), issueDate: dateField(input.invoice.issueDate, 'invoice.issueDate'), dueDate: dateField(input.invoice.dueDate, 'invoice.dueDate'), currency: currencyField(input.invoice.currency) }
  if (input.documentType.value === 'INVOICE' && invoice.number.normalizedValue === null) allIssues.push(issue('INVOICE_NUMBER_MISSING', 'invoice.number', 'ERROR', true, 'invoice number is required for invoices'))
  const amounts = { net: decimalField(input.amounts.net, 'amounts.net'), tax: decimalField(input.amounts.tax, 'amounts.tax'), gross: decimalField(input.amounts.gross, 'amounts.gross'), discount: decimalField(input.amounts.discount, 'amounts.discount'), withholding: decimalField(input.amounts.withholding, 'amounts.withholding') }
  const vatLines = input.vatLines.map((line, index) => ({ rate: decimalField(line.rate, `vatLines[${index}].rate`), base: decimalField(line.base, `vatLines[${index}].base`), tax: decimalField(line.tax, `vatLines[${index}].tax`) }))
  for (const [index, line] of vatLines.entries()) { if (line.rate.normalizedValue !== null && (line.rate.normalizedValue.startsWith('-') || decimalCompare(line.rate.normalizedValue, '100.00') > 0)) allIssues.push(issue('VAT_RATE_INVALID', `vatLines[${index}].rate`, 'ERROR', true, 'VAT rate must be between 0 and 100')) }
  const reconciliation = reconcileAmounts(amounts, vatLines)
  allIssues.push(...Object.values(supplier).flatMap((item) => item.issues), ...Object.values(invoice).flatMap((item) => item.issues), ...Object.values(amounts).flatMap((item) => item.issues), ...vatLines.flatMap((line) => Object.values(line).flatMap((item) => item.issues)), ...reconciliation.issues)
  const payment = { method: textField(input.payment.method, 'payment.method') }
  allIssues.push(...payment.method.issues)
  return { schemaVersion: 1, extraction: source, documentType, supplier, invoice, amounts, vatLines, payment, confidence: { overall: input.confidence.overall }, issues: allIssues, reconciliation, reviewStatus: deriveReviewStatus(allIssues, reconciliation.status) }
}
