import { useEffect, useMemo, useRef, useState } from 'react'
import { businessRules } from '../../app/businessRules'
import type { ClientListItem } from '../../features/clients/types'
import { findQuoteDuplicateGroups } from '../../features/duplicates/duplicateEngine'
import { saveQuoteWithLines } from '../../features/financial/financialWriteApi'
import type { PropertyListItem } from '../../features/properties/types'
import type { QuoteListItem } from '../../features/quotes/types'
import { buildQuoteLinePayloads, calculateQuoteSubtotal, createBlankQuoteLine, createLocalId, roundMoney, type QuoteLineFormState } from '../../features/quotes/quoteLineUtils'
import { V3BottomSheet, V3Field, V3Input, V3PrimaryAction, V3SecondaryAction, V3Select, V3Textarea } from '../components/V3Primitives'

interface Props { clients: ClientListItem[]; properties: PropertyListItem[]; quotes: QuoteListItem[]; onRefreshData: () => Promise<void>; onCompleted: () => Promise<void> | void; onCancel: () => void; onDirtyChange?: (dirty: boolean) => void; prefillClientId?: string; prefillPropertyId?: string }
export function V3QuoteCreateFlow({ clients, properties, quotes, onRefreshData, onCompleted, onCancel, onDirtyChange, prefillClientId = '', prefillPropertyId = '' }: Props) {
  const [clientId, setClientId] = useState(prefillClientId)
  const [propertyId, setPropertyId] = useState(prefillPropertyId)
  const [status, setStatus] = useState('draft')
  const [notes, setNotes] = useState('')
  const [lines, setLines] = useState<QuoteLineFormState[]>([createBlankQuoteLine()])
  const [busy, setBusy] = useState(false)
  const [error, setError] = useState<string | null>(null)
  const [duplicateId, setDuplicateId] = useState<string | null>(null)
  const [dirty, setDirty] = useState(false)
  const baselineRef = useRef(JSON.stringify({ clientId: prefillClientId, propertyId: prefillPropertyId, status: 'draft', notes: '', lines }))
  useEffect(() => { onDirtyChange?.(dirty); return () => onDirtyChange?.(false) }, [dirty, onDirtyChange])
  useEffect(() => { setDirty(JSON.stringify({ clientId, propertyId, status, notes, lines }) !== baselineRef.current) }, [clientId, propertyId, status, notes, lines])
  const subtotal = useMemo(() => calculateQuoteSubtotal(lines), [lines])
  const tax = roundMoney(subtotal * businessRules.defaultTaxRate)
  const total = roundMoney(subtotal + tax)
  const availableProperties = properties.filter((item) => item.client_id === clientId)
  function updateLine(index: number, field: keyof QuoteLineFormState, value: string) { setDirty(true); setLines((current) => current.map((line, itemIndex) => itemIndex === index ? { ...line, [field]: value } : line)) }
  async function submit(event: React.FormEvent) { event.preventDefault(); setError(null); if (!clientId) return setError('Selecciona un cliente.'); const payloadLines = buildQuoteLinePayloads(lines, 'QUOTE-PENDING'); if (!payloadLines?.length) return setError('Añade una línea válida.'); const id = createLocalId('QUOTE'); const finalLines = payloadLines.map((line, index) => ({ ...line, id: createLocalId('QUOTE-LINE'), quote_id: id, sort_order: index + 1 })); const client = clients.find((item) => item.id === clientId); const property = properties.find((item) => item.id === propertyId); const candidate = { id, display_code: null, lead_id: null, lead_display_code: null, lead_name: null, client_id: clientId, client_display_code: client?.display_code ?? null, client_name: client?.full_name ?? null, property_id: propertyId || null, property_display_code: property?.display_code ?? null, status, job_id: null, invoice_id: null, subtotal, tax_amount: tax, total, notes: notes.trim() || null, internal_notes: null, pricing_metadata: null, created_at: new Date().toISOString(), quote_lines: finalLines, lines: finalLines }; const duplicates = findQuoteDuplicateGroups(candidate, quotes); if (duplicates.length > 0) { setDuplicateId(duplicates[0]?.records?.[0]?.recordId ?? null); return } setBusy(true); try { await saveQuoteWithLines({ id, client_id: clientId, lead_id: null, property_id: propertyId || null, status, subtotal, tax_amount: tax, total, notes: notes.trim() || null }, finalLines); setDirty(false); await onRefreshData(); await onCompleted() } catch (caught) { setError(caught instanceof Error ? caught.message : 'No se pudo guardar el presupuesto.') } finally { setBusy(false) } }
  return <V3BottomSheet title="Nuevo presupuesto" onClose={onCancel}><form className="v3-form" onSubmit={(event) => void submit(event)}><p className="v3-section-copy">Contexto → líneas → importe → revisión. No se envía nada automáticamente.</p><V3Field label="Cliente"><V3Select value={clientId} onChange={(event) => { setClientId(event.target.value); setPropertyId('') }} required><option value="">Selecciona un cliente</option>{clients.map((item) => <option key={item.id} value={item.id}>{item.full_name}</option>)}</V3Select></V3Field><V3Field label="Inmueble"><V3Select value={propertyId} onChange={(event) => setPropertyId(event.target.value)}><option value="">Sin inmueble</option>{availableProperties.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</V3Select></V3Field><V3Field label="Estado"><V3Select value={status} onChange={(event) => setStatus(event.target.value)}><option value="draft">Borrador</option><option value="sent">Enviado</option></V3Select></V3Field>{lines.map((line, index) => <div className="v3-form-grid" key={line.local_id}><V3Field label="Concepto"><V3Input value={line.concept} onChange={(event) => updateLine(index, 'concept', event.target.value)} required /></V3Field><V3Field label="Cantidad"><V3Input inputMode="decimal" value={line.quantity} onChange={(event) => updateLine(index, 'quantity', event.target.value)} required /></V3Field><V3Field label="Unidad"><V3Input value={line.unit} onChange={(event) => updateLine(index, 'unit', event.target.value)} required /></V3Field><V3Field label="Precio unitario"><V3Input inputMode="decimal" value={line.unit_price} onChange={(event) => updateLine(index, 'unit_price', event.target.value)} required /></V3Field></div>)}<V3SecondaryAction type="button" onClick={() => setLines((current) => [...current, createBlankQuoteLine()])}>Añadir línea</V3SecondaryAction><V3Field label="Notas"><V3Textarea value={notes} onChange={(event) => setNotes(event.target.value)} /></V3Field><p className="v3-inline-message">Base {subtotal.toFixed(2)} € · IVA {tax.toFixed(2)} € · Total {total.toFixed(2)} €</p>{error ? <p className="v3-inline-message v3-inline-message--error" role="alert">{error}</p> : null}{duplicateId ? <p className="v3-inline-message" role="alert">Existe un posible presupuesto duplicado ({duplicateId}). No se ha guardado.</p> : null}<div className="v3-workspace-actions"><V3SecondaryAction type="button" onClick={onCancel}>Cancelar</V3SecondaryAction><V3PrimaryAction type="submit" disabled={busy}>{busy ? 'Guardando…' : 'Crear presupuesto'}</V3PrimaryAction></div></form></V3BottomSheet>
}
