import { useMemo, useState } from 'react'
import { businessRules } from '../../app/businessRules'; import type { ClientListItem } from '../../features/clients/types'; import { findQuoteDuplicateGroups } from '../../features/duplicates/duplicateEngine'; import { saveQuoteWithLines } from '../../features/financial/financialWriteApi'; import type { PropertyListItem } from '../../features/properties/types'; import type { QuoteListItem } from '../../features/quotes/types'; import { buildQuoteLinePayloads, calculateQuoteSubtotal, createBlankQuoteLine, createLocalId, roundMoney, type QuoteLineFormState } from '../../features/quotes/quoteLineUtils'
import { V3Field, V3Input, V3Select, V3Textarea } from '../components/V3Primitives'; import { V3StepFlow } from '../stepflow/V3StepFlow'
interface Props { clients: ClientListItem[]; properties: PropertyListItem[]; quotes: QuoteListItem[]; onRefreshData: () => Promise<void>; onCompleted: () => Promise<void> | void; onCancel: () => void; onDirtyChange?: (dirty: boolean) => void; prefillClientId?: string; prefillPropertyId?: string }
export function V3QuoteCreateFlow({ clients, properties, quotes, onRefreshData, onCompleted, onCancel, onDirtyChange, prefillClientId = '', prefillPropertyId = '' }: Props) {
  const [clientId, setClientId] = useState(prefillClientId); const [propertyId, setPropertyId] = useState(prefillPropertyId); const [status, setStatus] = useState('draft'); const [notes, setNotes] = useState(''); const [lines, setLines] = useState<QuoteLineFormState[]>([createBlankQuoteLine()]); const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null); const [duplicateId, setDuplicateId] = useState<string | null>(null)
  const subtotal = useMemo(() => calculateQuoteSubtotal(lines), [lines]); const tax = roundMoney(subtotal * businessRules.defaultTaxRate); const total = roundMoney(subtotal + tax); const availableProperties = properties.filter((item) => item.client_id === clientId)
  function updateLine(index: number, field: keyof QuoteLineFormState, value: string) { setLines((current) => current.map((line, itemIndex) => itemIndex === index ? { ...line, [field]: value } : line)); onDirtyChange?.(true) }
  async function submit() { setError(null); if (!clientId) return setError('Selecciona un cliente.'); const payloadLines = buildQuoteLinePayloads(lines, 'QUOTE-PENDING'); if (!payloadLines?.length) return setError('Añade una línea válida.'); const id = createLocalId('QUOTE'); const finalLines = payloadLines.map((line, index) => ({ ...line, id: createLocalId('QUOTE-LINE'), quote_id: id, sort_order: index + 1 })); const client = clients.find((item) => item.id === clientId); const property = properties.find((item) => item.id === propertyId); const candidate = { id, display_code: null, lead_id: null, lead_display_code: null, lead_name: null, client_id: clientId, client_display_code: client?.display_code ?? null, client_name: client?.full_name ?? null, property_id: propertyId || null, property_display_code: property?.display_code ?? null, status, job_id: null, invoice_id: null, subtotal, tax_amount: tax, total, notes: notes.trim() || null, internal_notes: null, pricing_metadata: null, created_at: new Date().toISOString(), quote_lines: finalLines, lines: finalLines }; const duplicates = findQuoteDuplicateGroups(candidate, quotes); if (duplicates.length) return setDuplicateId(duplicates[0]?.records?.[0]?.recordId ?? null); setBusy(true); try { await saveQuoteWithLines({ id, client_id: clientId, lead_id: null, property_id: propertyId || null, status, subtotal, tax_amount: tax, total, notes: notes.trim() || null }, finalLines); onDirtyChange?.(false); await onRefreshData(); await onCompleted() } catch (caught) { setError(caught instanceof Error ? caught.message : 'No se pudo guardar el presupuesto.') } finally { setBusy(false) } }
  return <V3StepFlow title="Nuevo presupuesto" onCancel={onCancel} onComplete={submit} error={error} busy={busy} completeLabel="Crear presupuesto" validateStep={(step) => step === 0 && !clientId ? 'Selecciona un cliente.' : step === 1 && !buildQuoteLinePayloads(lines, 'QUOTE-PENDING')?.length ? 'Añade una línea válida.' : null} steps={[
    { id: 'context', title: 'Contexto', description: 'Relaciona el presupuesto con cliente e inmueble.', content: <><V3Field label="Cliente"><V3Select value={clientId} onChange={(event) => { setClientId(event.target.value); setPropertyId(''); onDirtyChange?.(true) }} required autoFocus><option value="">Selecciona un cliente</option>{clients.map((item) => <option key={item.id} value={item.id}>{item.full_name}</option>)}</V3Select></V3Field><V3Field label="Inmueble"><V3Select value={propertyId} onChange={(event) => setPropertyId(event.target.value)}><option value="">Sin inmueble</option>{availableProperties.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</V3Select></V3Field><V3Field label="Estado"><V3Select value={status} onChange={(event) => setStatus(event.target.value)}><option value="draft">Borrador</option><option value="sent">Enviado</option></V3Select></V3Field></> },
    { id: 'lines', title: 'Líneas', description: 'Define el servicio y su precio.', content: <>{lines.map((line, index) => <div className="v3-step-flow__line" key={line.local_id}><V3Field label="Concepto"><V3Input value={line.concept} onChange={(event) => updateLine(index, 'concept', event.target.value)} required /></V3Field><V3Field label="Cantidad"><V3Input inputMode="decimal" value={line.quantity} onChange={(event) => updateLine(index, 'quantity', event.target.value)} required /></V3Field><V3Field label="Unidad"><V3Input value={line.unit} onChange={(event) => updateLine(index, 'unit', event.target.value)} required /></V3Field><V3Field label="Precio unitario"><V3Input inputMode="decimal" value={line.unit_price} onChange={(event) => updateLine(index, 'unit_price', event.target.value)} required /></V3Field></div>)}<button type="button" className="v3-action v3-action--secondary" onClick={() => setLines((current) => [...current, createBlankQuoteLine()])}>Añadir línea</button></> },
    { id: 'review', title: 'Notas y revisión', description: 'Comprueba el importe antes de crear el presupuesto.', content: <><p className="v3-inline-message">Base {subtotal.toFixed(2)} € · IVA {tax.toFixed(2)} € · Total {total.toFixed(2)} €</p><V3Field label="Notas"><V3Textarea value={notes} onChange={(event) => setNotes(event.target.value)} /></V3Field>{duplicateId ? <p className="v3-inline-message" role="alert">Existe un posible presupuesto duplicado ({duplicateId}). No se ha guardado.</p> : null}</> },
  ]} />
}
