import { useMemo, useState } from 'react'
import { businessRules } from '../../app/businessRules'
import { saveQuoteWithLines } from '../../features/financial/financialWriteApi'
import type { QuoteListItem } from '../../features/quotes/types'
import { buildQuoteLinePayloads, calculateQuoteSubtotal, createBlankQuoteLine, createLocalId, roundMoney, type QuoteLineFormState } from '../../features/quotes/quoteLineUtils'
import { V3BottomSheet, V3Field, V3Input, V3PrimaryAction, V3SecondaryAction, V3Select, V3Textarea } from '../components/V3Primitives'

interface Props { quote: QuoteListItem; onRefreshData: () => Promise<void>; onCompleted: () => Promise<void> | void; onCancel: () => void }
function initialLines(quote: QuoteListItem): QuoteLineFormState[] { const source = quote.lines?.length ? quote.lines : quote.quote_lines ?? []; return source.length ? source.map((line) => ({ local_id: line.id || createLocalId('LINE'), concept: line.concept, quantity: String(line.quantity), unit: line.unit ?? 'servicio', unit_price: String(line.unit_price) })) : [{ ...createBlankQuoteLine(), concept: '' }] }
export function V3QuoteEditFlow({ quote, onRefreshData, onCompleted, onCancel }: Props) {
  const [lines, setLines] = useState(initialLines(quote))
  const [status, setStatus] = useState(quote.status)
  const [notes, setNotes] = useState(quote.notes ?? '')
  const [busy, setBusy] = useState(false)
  const [error, setError] = useState<string | null>(null)
  const subtotal = useMemo(() => calculateQuoteSubtotal(lines), [lines])
  const tax = roundMoney(subtotal * businessRules.defaultTaxRate)
  const total = roundMoney(subtotal + tax)
  function updateLine(index: number, field: keyof QuoteLineFormState, value: string) { setLines((current) => current.map((line, itemIndex) => itemIndex === index ? { ...line, [field]: value } : line)) }
  async function submit(event: React.FormEvent) { event.preventDefault(); setError(null); const payloadLines = buildQuoteLinePayloads(lines, quote.id); if (!payloadLines?.length) return setError('Añade una línea válida.'); setBusy(true); try { await saveQuoteWithLines({ id: quote.id, client_id: quote.client_id, lead_id: quote.lead_id ?? null, property_id: quote.property_id ?? null, status, subtotal, tax_amount: tax, total, notes: notes.trim() || null, internal_notes: quote.internal_notes ?? null, pricing_metadata: quote.pricing_metadata ?? null }, payloadLines.map((line, index) => ({ ...line, id: createLocalId('QUOTE-LINE'), quote_id: quote.id, sort_order: index }))); await onRefreshData(); await onCompleted() } catch (caught) { setError(caught instanceof Error ? caught.message : 'No se pudo actualizar el presupuesto.') } finally { setBusy(false) } }
  return <V3BottomSheet title={`Editar ${quote.display_code ?? 'presupuesto'}`} onClose={onCancel}><form className="v3-form" onSubmit={(event) => void submit(event)}><p className="v3-section-copy">Se conserva la identidad y las relaciones del presupuesto. No se inventan estados de envío o lectura.</p>{lines.map((line, index) => <div className="v3-form-grid" key={line.local_id}><V3Field label="Concepto"><V3Input value={line.concept} onChange={(event) => updateLine(index, 'concept', event.target.value)} required /></V3Field><V3Field label="Cantidad"><V3Input inputMode="decimal" value={line.quantity} onChange={(event) => updateLine(index, 'quantity', event.target.value)} required /></V3Field><V3Field label="Unidad"><V3Input value={line.unit} onChange={(event) => updateLine(index, 'unit', event.target.value)} required /></V3Field><V3Field label="Precio unitario"><V3Input inputMode="decimal" value={line.unit_price} onChange={(event) => updateLine(index, 'unit_price', event.target.value)} required /></V3Field></div>)}<V3SecondaryAction type="button" onClick={() => setLines((current) => [...current, createBlankQuoteLine()])}>Añadir línea</V3SecondaryAction><V3Field label="Estado"><V3Select value={status} onChange={(event) => setStatus(event.target.value)}><option value="draft">Borrador</option><option value="sent">Enviado</option><option value="accepted">Aceptado</option><option value="rejected">Rechazado</option></V3Select></V3Field><V3Field label="Notas"><V3Textarea value={notes} onChange={(event) => setNotes(event.target.value)} /></V3Field><p className="v3-inline-message">Base {subtotal.toFixed(2)} € · IVA {tax.toFixed(2)} € · Total {total.toFixed(2)} €</p>{error ? <p className="v3-inline-message v3-inline-message--error" role="alert">{error}</p> : null}<div className="v3-workspace-actions"><V3SecondaryAction type="button" onClick={onCancel}>Cancelar</V3SecondaryAction><V3PrimaryAction type="submit" disabled={busy}>{busy ? 'Guardando…' : 'Guardar cambios'}</V3PrimaryAction></div></form></V3BottomSheet>
}
