import { useMemo, useState } from 'react'
import { businessRules } from '../../app/businessRules'; import { saveQuoteWithLines } from '../../features/financial/financialWriteApi'; import type { QuoteListItem } from '../../features/quotes/types'; import { buildQuoteLinePayloads, calculateQuoteSubtotal, createBlankQuoteLine, createLocalId, roundMoney, type QuoteLineFormState } from '../../features/quotes/quoteLineUtils'
import { V3Field, V3Input, V3Select, V3Textarea } from '../components/V3Primitives'; import { V3StepFlow } from '../stepflow/V3StepFlow'
interface Props { quote: QuoteListItem; onRefreshData: () => Promise<void>; onCompleted: () => Promise<void> | void; onCancel: () => void; onDirtyChange?: (dirty: boolean) => void }
function initialLines(quote: QuoteListItem): QuoteLineFormState[] { const source = quote.lines?.length ? quote.lines : quote.quote_lines ?? []; return source.length ? source.map((line) => ({ local_id: line.id || createLocalId('LINE'), concept: line.concept, quantity: String(line.quantity), unit: line.unit ?? 'servicio', unit_price: String(line.unit_price) })) : [{ ...createBlankQuoteLine(), concept: '' }] }
export function V3QuoteEditFlow({ quote, onRefreshData, onCompleted, onCancel, onDirtyChange }: Props) {
  const [lines, setLines] = useState(initialLines(quote)); const [status, setStatus] = useState(quote.status); const [notes, setNotes] = useState(quote.notes ?? ''); const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null); const subtotal = useMemo(() => calculateQuoteSubtotal(lines), [lines]); const tax = roundMoney(subtotal * businessRules.defaultTaxRate); const total = roundMoney(subtotal + tax)
  function updateLine(index: number, field: keyof QuoteLineFormState, value: string) { setLines((current) => current.map((line, itemIndex) => itemIndex === index ? { ...line, [field]: value } : line)); onDirtyChange?.(true) }
  async function submit() { setError(null); const payloadLines = buildQuoteLinePayloads(lines, quote.id); if (!payloadLines?.length) return setError('Añade una línea válida.'); setBusy(true); try { await saveQuoteWithLines({ id: quote.id, client_id: quote.client_id, lead_id: quote.lead_id ?? null, property_id: quote.property_id ?? null, status, subtotal, tax_amount: tax, total, notes: notes.trim() || null, internal_notes: quote.internal_notes ?? null, pricing_metadata: quote.pricing_metadata ?? null }, payloadLines.map((line, index) => ({ ...line, id: createLocalId('QUOTE-LINE'), quote_id: quote.id, sort_order: index + 1 }))); onDirtyChange?.(false); await onRefreshData(); await onCompleted() } catch (caught) { setError(caught instanceof Error ? caught.message : 'No se pudo actualizar el presupuesto.') } finally { setBusy(false) } }
  return <V3StepFlow title={`Editar ${quote.display_code ?? 'presupuesto'}`} onCancel={onCancel} onComplete={submit} error={error} busy={busy} completeLabel="Guardar cambios" validateStep={(step) => step === 0 && !buildQuoteLinePayloads(lines, quote.id)?.length ? 'Añade una línea válida.' : null} steps={[
    { id: 'lines', title: 'Líneas', description: 'Edita los conceptos conservando las relaciones.', content: <>{lines.map((line, index) => <div className="v3-step-flow__line" key={line.local_id}><V3Field label="Concepto"><V3Input value={line.concept} onChange={(event) => updateLine(index, 'concept', event.target.value)} required autoFocus /></V3Field><V3Field label="Cantidad"><V3Input inputMode="decimal" value={line.quantity} onChange={(event) => updateLine(index, 'quantity', event.target.value)} required /></V3Field><V3Field label="Unidad"><V3Input value={line.unit} onChange={(event) => updateLine(index, 'unit', event.target.value)} required /></V3Field><V3Field label="Precio unitario"><V3Input inputMode="decimal" value={line.unit_price} onChange={(event) => updateLine(index, 'unit_price', event.target.value)} required /></V3Field></div>)}<button type="button" className="v3-action v3-action--secondary" onClick={() => setLines((current) => [...current, createBlankQuoteLine()])}>Añadir línea</button></> },
    { id: 'status', title: 'Estado', description: 'Actualiza el estado visible del presupuesto.', content: <V3Field label="Estado"><V3Select value={status} onChange={(event) => setStatus(event.target.value)}><option value="draft">Borrador</option><option value="sent">Enviado</option><option value="accepted">Aceptado</option><option value="rejected">Rechazado</option></V3Select></V3Field> },
    { id: 'review', title: 'Notas y revisión', description: 'Confirma el resultado antes de guardar.', content: <><p className="v3-inline-message">Base {subtotal.toFixed(2)} € · IVA {tax.toFixed(2)} € · Total {total.toFixed(2)} €</p><V3Field label="Notas"><V3Textarea value={notes} onChange={(event) => setNotes(event.target.value)} /></V3Field></> },
  ]} />
}
