export type AppView =
  | 'dashboard'
  | 'alerts'
  | 'quarterly_closing'
  | 'annual_closing'
  | 'leads'
  | 'clients'
  | 'properties'
  | 'quotes'
  | 'jobs'
  | 'invoices'
  | 'expenses'
  | 'payments'
