#!/usr/bin/env bash
set -Eeuo pipefail

WORKFLOW=".github/workflows/cp51f-production-backup-restore.yml"
RESTORE="scripts/cp51f-restore-verify.sh"
BOOTSTRAP="scripts/cp51f-bootstrap-postgres17.sh"
SETUP="scripts/cp51f-production-backup-setup.sh"
JIT_CONTRACT="scripts/cp51f-production-backup-setup.contract.test.sh"
JIT_PROBE="scripts/cp51f-jit-prestate-readonly-probe.sh"
JIT_PROBE_TEST="scripts/cp51f-jit-prestate-readonly-probe.synthetic.test.sh"
JIT_PROBE_MOCK="scripts/cp51f-jit-prestate-readonly-probe.mock-curl.sh"
DIAGNOSTIC="scripts/cp51f-production-backup-setup.diagnostic.test.sh"
HTTP_DIAGNOSTIC="scripts/cp51f-management-api-http-diagnostic.test.sh"
HISTORY_SCHEMA="scripts/cp51f-history-guard.schema.test.sh"
SMOKE=".github/workflows/cp51f-executor-smoke.yml"
[[ -f "$WORKFLOW" && -f "$RESTORE" && -f "$BOOTSTRAP" && -f "$SETUP" && -f "$JIT_CONTRACT" && -f "$JIT_PROBE" && -f "$JIT_PROBE_TEST" && -f "$JIT_PROBE_MOCK" && -f "$DIAGNOSTIC" && -f "$HTTP_DIAGNOSTIC" && -f "$HISTORY_SCHEMA" && -f "$SMOKE" ]] || { printf 'CONTRACT_TEST=FAIL\n' >&2; exit 1; }

contains() { grep -Fq -- "$1" "$2"; }
not_contains() { ! grep -Fq -- "$1" "$2"; }
line_of() { grep -nF -- "$1" "$WORKFLOW" | head -n1 | cut -d: -f1; }

contains "tags:" "$WORKFLOW"
contains "cp51f-run-*" "$WORKFLOW"
not_contains "pull_request:" "$WORKFLOW"
not_contains "schedule:" "$WORKFLOW"
not_contains "workflow_dispatch:" "$WORKFLOW"
contains "contents: read" "$WORKFLOW"
contains "actions: read" "$WORKFLOW"
not_contains "actions: write" "$WORKFLOW"
contains "group: cp51f-production-backup-restore" "$WORKFLOW"
contains "cancel-in-progress: false" "$WORKFLOW"
contains "timeout-minutes: 30" "$WORKFLOW"
contains "CP51F_EXECUTION_ARMED" "$WORKFLOW"
contains "CP51F_EXPECTED_EXECUTION_SHA" "$WORKFLOW"
contains "CP51F_EXPECTED_EXECUTION_TAG" "$WORKFLOW"
contains "projectmanagmentnotion-CostaClean/costa-clean-app" "$WORKFLOW"
contains 'GITHUB_SHA' "$WORKFLOW"
contains 'GITHUB_REF_NAME' "$WORKFLOW"
contains 'GITHUB_RUN_ATTEMPT' "$WORKFLOW"
contains 'GITHUB_EVENT_NAME' "$WORKFLOW"
contains '.created // false' "$WORKFLOW"
contains '.forced // false' "$WORKFLOW"
contains '^cp51f-run-[0-9a-f]{32}$' "$WORKFLOW"
contains 'CP51F_BACKUP_AGE_RECIPIENT' "$WORKFLOW"
contains 'scripts/cp51f-bootstrap-postgres17.sh' "$WORKFLOW"
contains 'scripts/cp51f-bootstrap-postgres17.sh' "$SMOKE"
contains 'shellcheck scripts/cp51f-bootstrap-postgres17.sh' "$SMOKE"
contains 'ID:-' "$BOOTSTRAP"
contains 'ubuntu' "$BOOTSTRAP"
contains 'VERSION_ID:-' "$BOOTSTRAP"
contains '24.04' "$BOOTSTRAP"
contains 'noble-pgdg main' "$BOOTSTRAP"
contains 'ACCC4CF8.asc' "$BOOTSTRAP"
contains 'postgresql-17 postgresql-client-17' "$BOOTSTRAP"
contains 'PG_BIN_DIR=/usr/lib/postgresql/17/bin' "$BOOTSTRAP"
contains 'REQUIRED_TOOLS=(pg_dump pg_dumpall psql initdb pg_ctl)' "$BOOTSTRAP"
not_contains 'postgresql-16' "$BOOTSTRAP"
not_contains 'apt-get install -y --no-install-recommends age jq postgresql-client-17 postgresql-17' "$WORKFLOW"
contains 'SUPABASE_CP51F_TEMP_PAT' "$WORKFLOW"
not_contains 'inputs:' "$WORKFLOW"
contains 'scripts/cp51f-production-backup-setup.sh' "$WORKFLOW"
contains 'scripts/cp51f-production-backup-setup.sh --local-preflight' "$WORKFLOW"
contains 'CP51F_STATUS_FILE' "$WORKFLOW"
contains 'CP51F_RUNNER_RESULT' "$WORKFLOW"
contains 'CP51F_RUNNER_STAGE' "$WORKFLOW"
contains 'CP51F_RUNNER_CODE' "$WORKFLOW"
contains 'CP51F_TEMP_PAT_PRESENT' "$WORKFLOW"
contains 'TEMP_PAT_SECRET_PRESENCE=PASS' "$WORKFLOW"
contains 'scripts/cp51f-production-backup-setup.diagnostic.test.sh' "$SMOKE"
contains 'bash scripts/cp51f-production-backup-setup.contract.test.sh' "$SMOKE"
contains 'bash scripts/cp51f-jit-prestate-readonly-probe.synthetic.test.sh' "$SMOKE"
contains 'shellcheck scripts/cp51f-bootstrap-postgres17.sh' "$SMOKE"
contains 'scripts/cp51f-jit-prestate-readonly-probe.mock-curl.sh' "$SMOKE"
contains "readonly PROJECT_REF=\"wfxnwfcdjainpojhbdri\"" "$JIT_PROBE"
contains 'curl --config - --request GET' "$JIT_PROBE"
contains 'parse_jit_state() {' "$JIT_PROBE"
! grep -Eq -- '--request (POST|PUT|PATCH|DELETE)|/database/jit|supabase db|pg_dump' "$JIT_PROBE" || { printf 'CONTRACT_TEST=FAIL: probe exceeded GET-only scope\n' >&2; exit 1; }
contains "CP51F_PROBE_HTTP_401_TEST=PASS" "$JIT_PROBE_TEST"
contains "CP51F_PROBE_NETWORK_ERROR_TEST=PASS" "$JIT_PROBE_TEST"
contains 'reject_jit_state multi_json' "$JIT_CONTRACT"
contains 'scripts/cp51f-history-guard.schema.test.sh' "$SMOKE"
contains 'CP51F_HISTORY_SCHEMA_TESTS=PASS' "$HISTORY_SCHEMA"
contains 'scripts/cp51f-management-api-http-diagnostic.test.sh' "$SMOKE"
contains 'CP51F_MANAGEMENT_API_HTTP_DIAGNOSTIC_TESTS=PASS' "$HTTP_DIAGNOSTIC"
contains 'CP51F_DIAGNOSTIC_TESTS=PASS' "$DIAGNOSTIC"
if grep -Eq 'cat .*cp51f-runner\.log|path: .*cp51f-runner\.log' "$WORKFLOW"; then
  printf 'CONTRACT_TEST=FAIL: raw runner log publication\n' >&2
  exit 1
fi
contains 'actions/artifacts?name=' "$WORKFLOW"
contains 'STOP_ONE_SHOT_AUTHORIZATION_ALREADY_RESERVED_OR_CONSUMED' "$WORKFLOW"
contains 'STOP_ONE_SHOT_PREVIOUS_RUN_EXISTS' "$WORKFLOW"
contains 'jq -er' "$WORKFLOW"
contains 'type != "array"' "$WORKFLOW"
contains 'length == 0' "$WORKFLOW"
contains 'valid_page' "$WORKFLOW"
contains 'valid_run' "$WORKFLOW"
contains 'workflow_runs' "$WORKFLOW"
contains 'has("id")' "$WORKFLOW"
contains 'has("head_branch")' "$WORKFLOW"
contains 'has("head_sha")' "$WORKFLOW"
contains 'has("event")' "$WORKFLOW"
contains '(.id | type) == "number"' "$WORKFLOW"
contains '(.head_branch | type) == "string"' "$WORKFLOW"
contains '(.head_sha | type) == "string"' "$WORKFLOW"
contains '(.event | type) == "string"' "$WORKFLOW"
contains 'STOP_ONE_SHOT_HISTORY_GUARD_INVALID' "$WORKFLOW"
contains 'matching_previous_runs" =~ ^[0-9]+$' "$WORKFLOW"
not_contains '.[][]?' "$WORKFLOW"
not_contains '.workflow_runs[]?' "$WORKFLOW"
contains 'actions/workflows/cp51f-production-backup-restore.yml/runs?per_page=100' "$WORKFLOW"
contains ".head_branch == \$expected_tag" "$WORKFLOW"
contains ".head_sha == \$expected_sha" "$WORKFLOW"
contains '.event == "push"' "$WORKFLOW"
contains 'GITHUB_RUN_ID' "$WORKFLOW"
contains 'current_run_id' "$WORKFLOW"
contains 'cp51f-auth-reserved-' "$WORKFLOW"
contains 'cp51f-auth-consumed-' "$WORKFLOW"
contains 'retention-days: 90' "$WORKFLOW"
contains 'CP51F_SETUP_RESULT=' "$SETUP"
contains 'SETUP_RESULT="AWAITING_PAT_REVOCATION"' "$SETUP"
contains 'MANAGEMENT_API_HTTP_401' "$SETUP"
contains 'MANAGEMENT_API_HTTP_403' "$SETUP"
contains 'MANAGEMENT_API_HTTP_404' "$SETUP"
contains 'MANAGEMENT_API_HTTP_429' "$SETUP"
contains 'MANAGEMENT_API_HTTP_5XX' "$SETUP"
contains 'MANAGEMENT_API_NETWORK_ERROR' "$SETUP"
contains 'MANAGEMENT_API_UNEXPECTED_HTTP' "$SETUP"
contains "--write-out '%{http_code}'" "$SETUP"
contains 'MANAGEMENT_API_ERROR_CODE_FILE' "$SETUP"
not_contains "cat \"\$API_ERROR_FILE\"" "$SETUP"
if grep -Eq 'printf.*PAT' "$HTTP_DIAGNOSTIC"; then
  printf 'CONTRACT_TEST=FAIL: diagnostic PAT output\n' >&2
  exit 1
fi
contains 'scripts/cp51f-restore-verify.sh' "$WORKFLOW"
contains 'actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02' "$WORKFLOW"
contains 'retention-days: 7' "$WORKFLOW"
contains '.tar.gz.age' "$WORKFLOW"
not_contains 'set -x' "$WORKFLOW"
not_contains 'printenv' "$WORKFLOW"
not_contains 'GITHUB_ENV' "$WORKFLOW"
contains 'CP51F_BACKUP_RESTORE_VERIFIED_AWAITING_PAT_REVOCATION' "$WORKFLOW"
contains 'STOP_PRE_RELEASE_MIGRATION_STATE_CHANGED' "$WORKFLOW"
not_contains 'CP51F_COMPLETE' "$WORKFLOW"
not_contains 'Authorization B' "$WORKFLOW"
not_contains 'supabase db push' "$WORKFLOW"
not_contains 'migration repair' "$WORKFLOW"
contains 'roles.sql schema.sql data.sql history_schema.sql history_data.sql manifest.json restore-verification.json' "$WORKFLOW"
contains 'PG_BIN_DIR: /usr/lib/postgresql/17/bin' "$WORKFLOW"
contains "-h '' -k \$PGSOCKET" "$RESTORE"
contains 'STOP_BACKUP_INTEGRITY_FAILURE' "$RESTORE"
contains 'CP51F_RESTORE_ERROR:' "$RESTORE"
contains 'CP51F_RESTORE_RESULT=PASS' "$RESTORE"
contains '20260918155431' "$RESTORE"
contains 'cp43_canonical_state_reconciliation' "$RESTORE"
contains 'VERSION_NAME_MISMATCH' "$RESTORE"
contains 'cp43_migration_ledger_state' "$RESTORE"

arming_line="$(line_of 'CP51F_ONE_SHOT_GATE=PASS')"
one_shot_line="$arming_line"
local_preflight_line="$(line_of '- name: Run local backup preflight')"
pat_presence_line="$(line_of '- name: Verify temporary PAT presence')"
history_guard_line="$(line_of '- name: Previous run history guard')"
reservation_upload_line="$(line_of '- name: Upload reservation marker')"
marker_upload_line="$(line_of '- name: Upload consumed authorization marker')"
bootstrap_line="$(line_of 'scripts/cp51f-bootstrap-postgres17.sh')"
pat_line="$(line_of 'SUPABASE_CP51F_TEMP_PAT:')"
[[ -n "$arming_line" && -n "$one_shot_line" && -n "$history_guard_line" && -n "$reservation_upload_line" && -n "$local_preflight_line" && -n "$pat_presence_line" && -n "$marker_upload_line" && -n "$bootstrap_line" && -n "$pat_line" && "$arming_line" -lt "$history_guard_line" && "$history_guard_line" -lt "$reservation_upload_line" && "$reservation_upload_line" -lt "$bootstrap_line" && "$bootstrap_line" -lt "$local_preflight_line" && "$local_preflight_line" -lt "$pat_presence_line" && "$pat_presence_line" -lt "$marker_upload_line" && "$marker_upload_line" -lt "$pat_line" ]] || { printf 'CONTRACT_TEST=FAIL: fail-closed ordering\n' >&2; exit 1; }

if awk '/name: Arming and recipient gate/{active=1} /name: Install PostgreSQL 17 bootstrap/{active=0} active && /SUPABASE_CP51F_TEMP_PAT/{bad=1} END{exit bad+0}' "$WORKFLOW"; then
  :
else
  printf 'CONTRACT_TEST=FAIL: PAT appears before marker upload\n' >&2
  exit 1
fi

printf 'CP51F_WORKFLOW_CONTRACT=PASS\n'
printf 'CP51F_ONE_SHOT_REPLAY_SCENARIOS=PASS\n'
