import { useCallback, useEffect, useMemo, useState } from 'react'
import { listJobMaterialMovements, listMaterials, recordMaterialMovement, type Material, type MaterialMovement } from './materialOperationalApi'
import { directMaterialCost } from './materialOperational'

export function JobMaterialsPanel({ jobId, onChanged }: { jobId: string; onChanged: () => void }) {
  const [materials, setMaterials] = useState<Material[]>([]); const [movements, setMovements] = useState<MaterialMovement[]>([]); const [materialId, setMaterialId] = useState(''); const [quantity, setQuantity] = useState(''); const [occurredAt, setOccurredAt] = useState(() => new Date().toISOString().slice(0, 16)); const [notes, setNotes] = useState(''); const [error, setError] = useState<string | null>(null); const [saving, setSaving] = useState(false)
  const refresh = useCallback(async () => { try { const [catalog, ledger] = await Promise.all([listMaterials(), listJobMaterialMovements(jobId)]); setMaterials(catalog); setMovements(ledger); setError(null) } catch (loadError) { setError(loadError instanceof Error ? loadError.message : 'No se pudieron cargar los materiales del servicio.') } }, [jobId])
  useEffect(() => { void refresh() }, [refresh])
  const selected = materials.find((material) => material.id === materialId); const preview = selected && Number(quantity) > 0 ? Number(quantity) * Number(selected.default_unit_cost ?? 0) : 0; const materialCost = useMemo(() => movements.filter((movement) => movement.movement_type === 'consumption').reduce((sum, movement) => sum + directMaterialCost(movement), 0), [movements])
  async function save() { if (!selected || Number(quantity) <= 0) { setError('Selecciona material y una cantidad mayor que cero.'); return }; setSaving(true); try { await recordMaterialMovement({ material_id: selected.id, movement_type: 'consumption', quantity: Number(quantity), occurred_at: new Date(occurredAt).toISOString(), job_id: jobId, notes: notes.trim() || null, idempotency_key: `JOB-${jobId}-${crypto.randomUUID()}` }); setQuantity(''); setNotes(''); await refresh(); onChanged() } catch (saveError) { setError(saveError instanceof Error ? saveError.message : 'No se pudo registrar el consumo.') } finally { setSaving(false) } }
  return <section className="data-section" data-qa="job-materials"><div className="section-header"><div><h2>Materiales utilizados</h2><p>Coste directo de materiales: {materialCost.toFixed(2)} €</p></div></div><div className="lead-form cc-form-shell__grid"><label>Material<select value={materialId} onChange={(event) => setMaterialId(event.target.value)}><option value="">Selecciona material</option>{materials.filter((material) => material.status === 'active').map((material) => <option key={material.id} value={material.id}>{material.name}</option>)}</select></label><label>Cantidad<input type="number" min="0.01" step="0.01" value={quantity} onChange={(event) => setQuantity(event.target.value)} /></label><label>Fecha y hora<input type="datetime-local" value={occurredAt} onChange={(event) => setOccurredAt(event.target.value)} /></label><label>Nota opcional<input value={notes} onChange={(event) => setNotes(event.target.value)} /></label><p>Coste estimado: {preview.toFixed(2)} €</p><button type="button" className="primary-button" onClick={() => void save()} disabled={saving}>Registrar consumo</button></div>{movements.map((movement) => <article key={movement.id} className="cc-list-section__header"><div><strong>{materials.find((material) => material.id === movement.material_id)?.name ?? movement.material_id}</strong><p>{movement.quantity} · {new Date(movement.occurred_at).toLocaleString('es-ES')} · {movement.unit_cost_snapshot == null ? 'coste sin definir' : `${Number(movement.unit_cost_snapshot).toFixed(2)} €/unidad`}</p></div><strong>{directMaterialCost(movement).toFixed(2)} €</strong></article>)}{movements.length === 0 ? <p>No hay consumos registrados para este servicio.</p> : null}{error ? <p role="alert" className="form-error">{error}</p> : null}</section>
}
