import { useCallback, useEffect, useState } from 'react'
import { formatCurrency } from '../../app/displayFormat'
import { listJobMaterialMovements, listMaterials, type Material, type MaterialMovement } from './materialOperationalApi'
import { directMaterialCost } from './materialOperational'
import { comparePlannedMaterial } from './recurringOperational'

interface Requirement { id: string; material_id: string; planned_quantity: number; unit_cost_snapshot: number | null }

export function JobPlannedMaterialsPanel({ jobId }: { jobId: string }) {
  const [requirements, setRequirements] = useState<Requirement[]>([]); const [actual, setActual] = useState<MaterialMovement[]>([]); const [materials, setMaterials] = useState<Material[]>([]); const [error, setError] = useState<string | null>(null)
  const refresh = useCallback(async () => { try { const { getSupabaseClient } = await import('../../lib/supabase'); const { client, error: clientError } = getSupabaseClient(); if (!client) throw new Error(clientError ?? 'No se pudo inicializar Supabase.'); const [req, movements, catalog] = await Promise.all([client.from('job_material_requirements').select('*').eq('job_id', jobId).order('created_at'), listJobMaterialMovements(jobId), listMaterials()]); if (req.error) throw req.error; setRequirements((req.data ?? []) as Requirement[]); setActual(movements); setMaterials(catalog); setError(null) } catch (loadError) { setError(loadError instanceof Error ? loadError.message : 'No se pudo cargar el plan de materiales.') } }, [jobId])
  useEffect(() => { void refresh() }, [refresh])
  return <section className="data-section" data-qa="job-planned-materials"><div className="section-header"><div><h2>Material previsto</h2><p>Requerimiento planificado; el consumo real se registra por separado.</p></div></div>{requirements.map((requirement) => { const material = materials.find((item) => item.id === requirement.material_id); const movements = actual.filter((item) => item.material_id === requirement.material_id && item.movement_type === 'consumption'); const actualQuantity = movements.reduce((sum, item) => sum + Number(item.quantity), 0); const actualCost = movements.reduce((sum, item) => sum + directMaterialCost(item), 0); const comparison = comparePlannedMaterial(Number(requirement.planned_quantity), Number(requirement.unit_cost_snapshot ?? material?.default_unit_cost ?? 0), actualQuantity, actualQuantity > 0 ? actualCost / actualQuantity : Number(requirement.unit_cost_snapshot ?? 0), material?.unit === undefined || material?.unit === material?.unit); return <article key={requirement.id} className="cc-list-section__header"><div><strong>{material?.name ?? requirement.material_id}</strong><p>Previsto: {requirement.planned_quantity} {material?.unit ?? ''} · Real: {actualQuantity} · Variación: {comparison.quantityVariance ?? '—'}</p></div><div><strong>{formatCurrency(comparison.plannedCost)}</strong><p>Real {formatCurrency(comparison.actualCost)}</p></div></article>})}{requirements.length === 0 ? <p>No hay materiales previstos para este servicio.</p> : null}{error ? <p role="alert" className="form-error">{error}</p> : null}</section>
}
