import { useCallback, useEffect, useState } from 'react'
import { formatCurrency } from '../../app/displayFormat'
import { getMaterialNeedsForecast, getOperationalForecast, getTeamWorkloadForecast } from './recurringOperationalApi'

export function PlanningForecastPanels() {
  const [days, setDays] = useState(30); const [forecast, setForecast] = useState<Record<string, number> | null>(null); const [needs, setNeeds] = useState<Array<Record<string, string | number>>>([]); const [workload, setWorkload] = useState<Array<Record<string, string | number>>>([]); const [error, setError] = useState<string | null>(null)
  const refresh = useCallback(async () => { const through = new Date(Date.now() + days * 86_400_000).toISOString().slice(0, 10); try { const [nextForecast, nextNeeds, nextWorkload] = await Promise.all([getOperationalForecast(new Date().toISOString().slice(0, 10), through), getMaterialNeedsForecast(through), getTeamWorkloadForecast(through)]); setForecast(nextForecast as Record<string, number>); setNeeds((nextNeeds ?? []) as Array<Record<string, string | number>>); setWorkload((nextWorkload ?? []) as Array<Record<string, string | number>>); setError(null) } catch (loadError) { setError(loadError instanceof Error ? loadError.message : 'El forecast operativo aún no está disponible.') } }, [days])
  useEffect(() => { void refresh() }, [refresh])
  return <section className="data-section" data-qa="planning-forecasts"><div className="section-header"><div><h2>Necesidades próximas</h2><p>Planificación factual; no reserva ni descuenta stock.</p></div><label>Horizonte<select value={days} onChange={(event) => setDays(Number(event.target.value))}><option value="30">30 días</option><option value="60">60 días</option><option value="90">90 días</option></select></label></div>{error ? <p role="alert" className="form-error">{error}</p> : forecast ? <><div className="cc-client-workspace__ledger-grid"><div className="detail-row"><span className="detail-label">Visitas previstas</span><strong>{forecast.scheduled_visit_count ?? 0}</strong></div><div className="detail-row"><span className="detail-label">Horas previstas</span><strong>{forecast.planned_worker_hours ?? 0} h</strong></div><div className="detail-row"><span className="detail-label">Coste personal</span><strong>{formatCurrency(forecast.planned_labor_cost ?? 0)}</strong></div><div className="detail-row"><span className="detail-label">Materiales previstos</span><strong>{formatCurrency(forecast.planned_material_cost ?? 0)}</strong></div><div className="detail-row"><span className="detail-label">Coste directo previsto</span><strong>{formatCurrency(forecast.planned_direct_cost ?? 0)}</strong></div></div><div className="cc-client-workspace__focus-list"><article className="cc-client-workspace__focus-card"><span>Materiales</span>{needs.length === 0 ? <strong>Sin necesidades registradas</strong> : needs.map((need) => <strong key={String(need.material_id)}>{String(need.material_name)}: {Number(need.shortage_quantity) > 0 ? `faltan ${need.shortage_quantity}` : 'stock suficiente'}</strong>)}</article><article className="cc-client-workspace__focus-card"><span>Horas de equipo</span>{workload.length === 0 ? <strong>Sin horas planificadas</strong> : workload.map((item) => <strong key={String(item.team_member_id)}>{String(item.worker_name)}: {item.planned_hours} h</strong>)}</article></div></> : <p>Cargando forecast...</p>}</section>
}
