import { useCallback, useEffect, useMemo, useState } from 'react'
import { formatCurrency } from '../../app/displayFormat'
import { listMaterials, type Material } from './materialOperationalApi'
import { listTeamMembers } from './teamOperationalApi'
import type { TeamMember } from './teamOperational'
import { listOperationalRecurringPlans, saveRecurringOperationalTemplate } from './recurringOperationalApi'
import { plannedDirectCost, plannedLaborCost, plannedMaterialCost, type RecurringMaterialTemplate, type RecurringTeamTemplate } from './recurringOperational'

export function RecurringOperationalTemplateEditor({ planId, revenueBase }: { planId: string; revenueBase: number }) {
  const [members, setMembers] = useState<TeamMember[]>([])
  const [materials, setMaterials] = useState<Material[]>([])
  const [team, setTeam] = useState<RecurringTeamTemplate[]>([])
  const [plannedMaterials, setPlannedMaterials] = useState<RecurringMaterialTemplate[]>([])
  const [error, setError] = useState<string | null>(null)
  const [saving, setSaving] = useState(false)
  const refresh = useCallback(async () => { try { const [availableMembers, availableMaterials, plans] = await Promise.all([listTeamMembers(), listMaterials(), listOperationalRecurringPlans()]); const plan = plans.find((item) => item.id === planId); setMembers(availableMembers); setMaterials(availableMaterials); setTeam(plan?.team_templates ?? []); setPlannedMaterials(plan?.material_templates ?? []); setError(null) } catch (loadError) { setError(loadError instanceof Error ? loadError.message : 'No se pudo cargar la plantilla operativa.') } }, [planId])
  useEffect(() => { void refresh() }, [refresh])
  const labor = plannedLaborCost(team); const materialCost = plannedMaterialCost(plannedMaterials); const total = plannedDirectCost(team, plannedMaterials); const contribution = revenueBase - total; const margin = revenueBase > 0 ? contribution / revenueBase * 100 : null
  const memberIds = useMemo(() => new Set(team.map((item) => item.team_member_id)), [team]); const materialIds = useMemo(() => new Set(plannedMaterials.map((item) => item.material_id)), [plannedMaterials])
  function addWorker(memberId: string) { const member = members.find((item) => item.id === memberId); if (!member || memberIds.has(memberId)) return; setTeam([...team, { team_member_id: memberId, planned_minutes: 60, default_hourly_cost: member.default_hourly_cost }]) }
  function addMaterial(materialId: string) { const material = materials.find((item) => item.id === materialId); if (!material || materialIds.has(materialId)) return; setPlannedMaterials([...plannedMaterials, { material_id: materialId, planned_quantity: 1, default_unit_cost: material.default_unit_cost, unit: material.unit }]) }
  async function save() { setSaving(true); try { await saveRecurringOperationalTemplate(planId, team, plannedMaterials); setError(null) } catch (saveError) { setError(saveError instanceof Error ? saveError.message : 'No se pudo guardar la plantilla operativa.') } finally { setSaving(false) } }
  return <section className="data-section" data-qa="recurring-operational-template"><div className="section-header"><div><h4>Operativa habitual</h4><p>Planificado, no ejecutado: personal {formatCurrency(labor)} · materiales {formatCurrency(materialCost)} · directo {formatCurrency(total)} · margen {margin == null ? '—' : `${margin.toFixed(2)} %`}</p></div><button type="button" className="primary-button" onClick={() => void save()} disabled={saving}>Guardar operativa</button></div><div className="lead-form cc-form-shell__grid"><label>Equipo previsto<select value="" onChange={(event) => addWorker(event.target.value)}><option value="">Añadir operario</option>{members.filter((member) => member.status === 'active' && !memberIds.has(member.id)).map((member) => <option key={member.id} value={member.id}>{member.full_name}</option>)}</select></label>{team.map((item, index) => <label key={item.team_member_id}>Tiempo previsto<input type="number" min="1" step="15" value={item.planned_minutes} onChange={(event) => setTeam(team.map((entry, entryIndex) => entryIndex === index ? { ...entry, planned_minutes: Number(event.target.value) } : entry))} /><small>{members.find((member) => member.id === item.team_member_id)?.full_name ?? item.team_member_id} · Coste/h {formatCurrency(item.hourly_cost_override ?? item.default_hourly_cost ?? 0)}</small></label>)}</div><div className="lead-form cc-form-shell__grid"><label>Material previsto<select value="" onChange={(event) => addMaterial(event.target.value)}><option value="">Añadir material</option>{materials.filter((material) => material.status === 'active' && !materialIds.has(material.id)).map((material) => <option key={material.id} value={material.id}>{material.name}</option>)}</select></label>{plannedMaterials.map((item, index) => <label key={item.material_id}>Cantidad prevista<input type="number" min="0.01" step="0.01" value={item.planned_quantity} onChange={(event) => setPlannedMaterials(plannedMaterials.map((entry, entryIndex) => entryIndex === index ? { ...entry, planned_quantity: Number(event.target.value) } : entry))} /><small>{materials.find((material) => material.id === item.material_id)?.name ?? item.material_id} · {formatCurrency(item.unit_cost_override ?? item.default_unit_cost ?? 0)} / unidad</small></label>)}</div>{error ? <p role="alert" className="form-error">{error}</p> : null}</section>
}
