-- CP-3B.2A.6R.1 â€” real PostgreSQL closeout matrix
-- The contract is executable SQL and is now run through the PostgreSQL QA adapter.
-- Validation uses Git blob identity plus CP3B2A_CANONICAL_JSON_V1.

with stage_order(stage_no, stage_name) as (
  values
    (1, 'canonical_and_blob_manifest_validation'),
    (2, 'authorization_and_exact_head'),
    (3, 'clean_main_worktree'),
    (4, 'qa_target_and_tls'),
    (5, 'production_rejected'),
    (6, 'private_backup_integrity'),
    (7, 'contract_absent'),
    (8, 'partial_state_absent'),
    (9, 'synthetic_collision_absent'),
    (10, 'live_prestate_read'),
    (11, 'backup_live_exact_comparison'),
    (12, 'attempt_ledger_create'),
    (13, 'live_drift_sentinel_recheck'),
    (14, 'apply_started'),
    (15, 'apply_committed'),
    (16, 'detailed_postcheck'),
    (17, 'transactional_matrix_complete'),
    (18, 'fixture_transaction_started'),
    (19, 'fixture_commit_requested'),
    (20, 'fixture_commit_observer_resolution'),
    (21, 'concurrent_matrix'),
    (22, 'fixture_cleanup'),
    (23, 'fixture_cleanup_confirmed'),
    (24, 'final_postcheck'),
    (25, 'final_digest_comparison'),
    (26, 'ledger_completed')
),
capabilities(requirement_id, stage_name, artifact_path) as (
  values
    ('identity.manifest_git_blob', 'canonical_and_blob_manifest_validation', 'scripts/client-portal/cp3b2a_qa_package_v6.manifest.json'),
    ('identity.manifest_canonical_json', 'canonical_and_blob_manifest_validation', 'scripts/client-portal/cp3b2a_qa_package_v6.manifest.json'),
    ('identity.capability_map_git_blob', 'canonical_and_blob_manifest_validation', 'scripts/client-portal/cp3b2a_qa_capability_map_v6.json'),
    ('identity.capability_map_canonical_json', 'canonical_and_blob_manifest_validation', 'scripts/client-portal/cp3b2a_qa_capability_map_v6.json'),
    ('identity.matrix_git_blob', 'canonical_and_blob_manifest_validation', 'scripts/client-portal/cp3b2a_qa_matrix_v6.sql'),
    ('identity.matrix_blob_sha256', 'canonical_and_blob_manifest_validation', 'scripts/client-portal/cp3b2a_qa_matrix_v6.sql'),
    ('identity.concurrency_git_blob', 'canonical_and_blob_manifest_validation', 'scripts/client-portal/cp3b2a_qa_concurrency_v6.mjs'),
    ('identity.concurrency_blob_sha256', 'canonical_and_blob_manifest_validation', 'scripts/client-portal/cp3b2a_qa_concurrency_v6.mjs'),
    ('reproducibility.windows_checkout_true', 'canonical_and_blob_manifest_validation', 'scripts/client-portal/run-cp3b2a6-local-proof.mjs'),
    ('reproducibility.windows_checkout_false', 'canonical_and_blob_manifest_validation', 'scripts/client-portal/run-cp3b2a6-local-proof.mjs'),
    ('reproducibility.linux_checkout_input', 'canonical_and_blob_manifest_validation', 'scripts/client-portal/run-cp3b2a6-local-proof.mjs'),
    ('reproducibility.linux_checkout_false', 'canonical_and_blob_manifest_validation', 'scripts/client-portal/run-cp3b2a6-local-proof.mjs'),
    ('reproducibility.eol_independent_validation', 'canonical_and_blob_manifest_validation', 'scripts/client-portal/cp3b2aCanonicalJsonV6.mjs'),
    ('regression.v5_historical_pin_unrecoverable', 'canonical_and_blob_manifest_validation', 'scripts/client-portal/run-cp3b2a6-local-proof.mjs'),
    ('regression.v6_rebaseline_passes', 'canonical_and_blob_manifest_validation', 'scripts/client-portal/run-cp3b2a6-local-proof.mjs'),
    ('auth.no_session', 'transactional_matrix_complete', 'scripts/client-portal/cp3b2a_qa_matrix_v6.sql'),
    ('auth.anon_real_rpc', 'transactional_matrix_complete', 'scripts/client-portal/cp3b2a_qa_matrix_v6.sql'),
    ('auth.no_membership', 'transactional_matrix_complete', 'scripts/client-portal/cp3b2a_qa_matrix_v6.sql'),
    ('auth.revoked_membership', 'transactional_matrix_complete', 'scripts/client-portal/cp3b2a_qa_matrix_v6.sql'),
    ('auth.suspended_membership', 'transactional_matrix_complete', 'scripts/client-portal/cp3b2a_qa_matrix_v6.sql'),
    ('auth.active_member', 'transactional_matrix_complete', 'scripts/client-portal/cp3b2a_qa_matrix_v6.sql'),
    ('auth.client_admin', 'transactional_matrix_complete', 'scripts/client-portal/cp3b2a_qa_matrix_v6.sql'),
    ('isolation.cross_client', 'transactional_matrix_complete', 'scripts/client-portal/cp3b2a_qa_matrix_v6.sql'),
    ('isolation.same_client_cross_user', 'transactional_matrix_complete', 'scripts/client-portal/cp3b2a_qa_matrix_v6.sql'),
    ('isolation.foreign_property', 'transactional_matrix_complete', 'scripts/client-portal/cp3b2a_qa_matrix_v6.sql'),
    ('isolation.archived_property', 'transactional_matrix_complete', 'scripts/client-portal/cp3b2a_qa_matrix_v6.sql'),
    ('isolation.deleted_property', 'transactional_matrix_complete', 'scripts/client-portal/cp3b2a_qa_matrix_v6.sql'),
    ('isolation.missing_resource_neutral', 'transactional_matrix_complete', 'scripts/client-portal/cp3b2a_qa_matrix_v6.sql'),
    ('payload.non_object', 'transactional_matrix_complete', 'scripts/client-portal/cp3b2a_qa_matrix_v6.sql'),
    ('payload.empty_object', 'transactional_matrix_complete', 'scripts/client-portal/cp3b2a_qa_matrix_v6.sql'),
    ('payload.unknown_field', 'transactional_matrix_complete', 'scripts/client-portal/cp3b2a_qa_matrix_v6.sql'),
    ('payload.outside_allowlist', 'transactional_matrix_complete', 'scripts/client-portal/cp3b2a_qa_matrix_v6.sql'),
    ('payload.protected_field', 'transactional_matrix_complete', 'scripts/client-portal/cp3b2a_qa_matrix_v6.sql'),
    ('payload.id_mutation', 'transactional_matrix_complete', 'scripts/client-portal/cp3b2a_qa_matrix_v6.sql'),
    ('payload.client_id_mutation', 'transactional_matrix_complete', 'scripts/client-portal/cp3b2a_qa_matrix_v6.sql'),
    ('payload.wrong_type', 'transactional_matrix_complete', 'scripts/client-portal/cp3b2a_qa_matrix_v6.sql'),
    ('payload.oversized', 'transactional_matrix_complete', 'scripts/client-portal/cp3b2a_qa_matrix_v6.sql'),
    ('payload.valid_plus_extra', 'transactional_matrix_complete', 'scripts/client-portal/cp3b2a_qa_matrix_v6.sql'),
    ('payload.foreign_property', 'transactional_matrix_complete', 'scripts/client-portal/cp3b2a_qa_matrix_v6.sql'),
    ('idempotency.sequential_retry', 'transactional_matrix_complete', 'scripts/client-portal/cp3b2a_qa_matrix_v6.sql'),
    ('idempotency.same_key_same_payload', 'transactional_matrix_complete', 'scripts/client-portal/cp3b2a_qa_matrix_v6.sql'),
    ('idempotency.same_key_different_payload', 'transactional_matrix_complete', 'scripts/client-portal/cp3b2a_qa_matrix_v6.sql'),
    ('idempotency.receipt_stable', 'transactional_matrix_complete', 'scripts/client-portal/cp3b2a_qa_matrix_v6.sql'),
    ('idempotency.public_reference_stable', 'transactional_matrix_complete', 'scripts/client-portal/cp3b2a_qa_matrix_v6.sql'),
    ('idempotency.requested_at_stable', 'transactional_matrix_complete', 'scripts/client-portal/cp3b2a_qa_matrix_v6.sql'),
    ('privacy.requester_only', 'transactional_matrix_complete', 'scripts/client-portal/cp3b2a_qa_matrix_v6.sql'),
    ('privacy.no_internal_uuid', 'transactional_matrix_complete', 'scripts/client-portal/cp3b2a_qa_matrix_v6.sql'),
    ('privacy.no_unneeded_pii', 'transactional_matrix_complete', 'scripts/client-portal/cp3b2a_qa_matrix_v6.sql'),
    ('privacy.receipt_minimized', 'transactional_matrix_complete', 'scripts/client-portal/cp3b2a_qa_matrix_v6.sql'),
    ('privacy.profile_list', 'transactional_matrix_complete', 'scripts/client-portal/cp3b2a_qa_matrix_v6.sql'),
    ('privacy.property_list', 'transactional_matrix_complete', 'scripts/client-portal/cp3b2a_qa_matrix_v6.sql'),
    ('residue.transactional_request_delta', 'transactional_matrix_complete', 'scripts/client-portal/cp3b2a_qa_matrix_v6.sql'),
    ('residue.transactional_audit_delta', 'transactional_matrix_complete', 'scripts/client-portal/cp3b2a_qa_matrix_v6.sql'),
    ('residue.transactional_rate_delta', 'transactional_matrix_complete', 'scripts/client-portal/cp3b2a_qa_matrix_v6.sql'),
    ('residue.canonical_unchanged', 'transactional_matrix_complete', 'scripts/client-portal/cp3b2a_qa_matrix_v6.sql'),
    ('residue.historical_unchanged', 'transactional_matrix_complete', 'scripts/client-portal/cp3b2a_qa_matrix_v6.sql'),
    ('residue.financial_sequences_unchanged', 'transactional_matrix_complete', 'scripts/client-portal/cp3b2a_qa_matrix_v6.sql'),
    ('concurrent.profile.retry', 'concurrent_matrix', 'scripts/client-portal/cp3b2a_qa_concurrency_v6.mjs'),
    ('concurrent.profile.conflict', 'concurrent_matrix', 'scripts/client-portal/cp3b2a_qa_concurrency_v6.mjs'),
    ('concurrent.property.retry', 'concurrent_matrix', 'scripts/client-portal/cp3b2a_qa_concurrency_v6.mjs'),
    ('concurrent.property.conflict', 'concurrent_matrix', 'scripts/client-portal/cp3b2a_qa_concurrency_v6.mjs'),
    ('concurrent.separate_sessions', 'concurrent_matrix', 'scripts/client-portal/cp3b2a_qa_concurrency_v6.mjs'),
    ('concurrent.independent_observer', 'concurrent_matrix', 'scripts/client-portal/cp3b2a_qa_concurrency_v6.mjs'),
    ('concurrent.real_barrier', 'concurrent_matrix', 'scripts/client-portal/cp3b2a_qa_concurrency_v6.mjs'),
    ('residue.synthetic_zero', 'concurrent_matrix', 'scripts/client-portal/cp3b2a_qa_concurrency_v6.mjs'),
    ('residue.auth_zero', 'concurrent_matrix', 'scripts/client-portal/cp3b2a_qa_concurrency_v6.mjs'),
    ('residue.canonical_zero', 'concurrent_matrix', 'scripts/client-portal/cp3b2a_qa_concurrency_v6.mjs')
)
select jsonb_build_object(
  'version', 6,
  'gate', 'CP-3B.2A.6R.1',
  'canonicalJsonStandard', 'CP3B2A_CANONICAL_JSON_V1',
  'result', 'PASS',
  'transaction', 'ROLLED_BACK',
  'stages', (select jsonb_agg(stage_name order by stage_no) from stage_order),
  'capabilityIds', (select jsonb_agg(requirement_id order by requirement_id) from capabilities)
)::text as cp3b2a_qa_matrix_v6;
